### ISSUE TITLE
ImportWarning when importing zmq

### ISSUE THREAD

**Issue by alexholdenmiller** [zeromq/pyzmq#1004]
Importing zmq within my scripts frequently gives the message:
`ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__`

This doesn't happen in interactive mode, but e.g. the following script (filtering the warning above to cause an error to get the traceback)...
```
import unittest
class Test(unittest.TestCase):
    def test_1(self):
        import warnings
        warnings.filterwarnings('error')
        import zmq
unittest.main()
```
...results in...
```
Traceback (most recent call last):
  File "test.py", line 8, in test_1
    import zmq
  File "/Users/ahm/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/Users/ahm/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/Users/ahm/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/Users/ahm/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/Users/ahm/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 33, in select_backend
    reraise(ImportError, ImportError("Importing %s failed with %s" % (name, e)), exc_info[2])
  File "/Users/ahm/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 33, in reraise
    raise value.with_traceback(tb)
  File "/Users/ahm/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/Users/ahm/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
  File "zmq/backend/cython/error.pyx", line 32, in init zmq.backend.cython.error (zmq/backend/cython/error.c:1228)
ImportError: Importing zmq.backend.cython failed with can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
```

Reproduced in:
anaconda 4.3.1, python 3.6.0 on Mac OSX with zmq.zmq_version() => 4.1.6
anaconda 4.3.0, python 3.6.0 on CentOS7 with zmq.zmq_version() => 4.1.5

**Comment by minrk** [comment]
I suspect this is a Cython issue, where the generated modules only have the expected metadata for Python < 3.6.
