### ISSUE TITLE
PyZmq with PGM on Ubuntu

### ISSUE THREAD

**Issue by pepijndevos** [zeromq/pyzmq#1005]
Neither Ubuntu's `python3-zmq` nor PyPi's `pyzmq` seem to be built with the `--with-pgm` option, giving `zmq.error.ZMQError: Protocol not supported` on instantiating a PGM socket.

The suggested approach is to build everything from source. So I Installed OpenPGM from Ubuntu package, and installed `libzmq-4.2.2` with `./configure --with-pgm --prefix SOMEPATH` followed by a `make install`. After several tries, this seemed to work.

Next I downloaded `pyzmq-14.7.0` and ran `python3 setup.py build --zmq=SOMEPATH`.
Even though I downloaded a release, it asked for Cygwin, which I `pip install`'d, only to be confronted by `zmq/backend/cython/context.pyx:119:24: 'underlying' is not a constant, variable 
or function identifier`.
I [googled around](http://askubuntu.com/questions/739340/pyzmq-compiling-error), and it seems this line was removed, so I did the same.
This caused PyZmq to build, so I finished it off with a `python3 setup.py install`.

However, now when I `import zmq` I get super weird errors:
```
Traceback (most recent call last):
  File "server.py", line 1, in <module>
    import zmq
  File "/home/pepijn/code/netsys/finproj/env/lib/python3.5/site-packages/zmq/__init__.py", line 36, in <module>
    from zmq import sugar
  File "/home/pepijn/code/netsys/finproj/env/lib/python3.5/site-packages/zmq/sugar/__init__.py", line 7, in <module>
    from zmq.sugar import (
  File "/home/pepijn/code/netsys/finproj/env/lib/python3.5/site-packages/zmq/sugar/constants.py", line 31, in <module>
    DRAFT_API = constants.DRAFT_API
AttributeError: module 'zmq.backend.cython.constants' has no attribute 'DRAFT_API'
```
And all I wanted is a PGM socket...

**Comment by pepijndevos** [comment]
Good job... the "releases" tab has a version from 2015. With an actual recent version, it seems to work. Please fix your release page.
