### ISSUE TITLE
pyzmq 17 doesn't work with uvloop

### ISSUE THREAD

**Issue by jkbbwr** [zeromq/pyzmq#1047]
Smallest reproducible example

```
from zmq.asyncio import Context
import asyncio
import zmq

ctx = Context()
import uvloop; asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

async def recv():
    s = ctx.socket(zmq.PUB)
    s.bind("tcp://127.0.0.1:5555")
    while True:
        await s.send_multipart([b"wow", b"magic"])
        await asyncio.sleep(1)

loop = asyncio.get_event_loop()
loop.run_until_complete(recv())
```

Produces the following exception
```
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 568, in uvloop.loop.Loop._add_reader (uvloop/loop.c:14392)
KeyError: <zmq.sugar.socket.Socket object at 0x7f5001643c10>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    loop.run_until_complete(recv())
  File "uvloop/loop.pyx", line 1203, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25632)
  File "test.py", line 9, in recv
    s = ctx.socket(zmq.PUB)
  File "/home/jakob/.virtualenvs/tempenv-05e91538950e1/lib/python3.6/site-packages/zmq/sugar/context.py", line 146, in socket
    s = self._socket_class(self, socket_type, **kwargs)
  File "/home/jakob/.virtualenvs/tempenv-05e91538950e1/lib/python3.6/site-packages/zmq/_future.py", line 132, in __init__
    self._init_io_state()
  File "/home/jakob/.virtualenvs/tempenv-05e91538950e1/lib/python3.6/site-packages/zmq/asyncio/__init__.py", line 53, in _init_io_state
    self.io_loop.add_reader(self._shadow_sock, lambda : self._handle_events(0, 0))
  File "uvloop/loop.pyx", line 1902, in uvloop.loop.Loop.add_reader (uvloop/loop.c:35558)
  File "uvloop/loop.pyx", line 570, in uvloop.loop.Loop._add_reader (uvloop/loop.c:14439)
TypeError: an integer is required
```

**Comment by minrk** [comment]
Looks like a bug in uvloop that it doesn't accept sockets with a `.fileno()` method.

[This example](https://docs.python.org/3/library/asyncio-eventloop.html#watch-a-file-descriptor-for-read-events) from the Python asyncio docs fails with the same error when run with uvloop.

I've opened a PR [upstream](https://github.com/MagicStack/uvloop/pull/101), but I think I can workaround the bug on this side (#1048).

**Comment by jkbbwr** [comment]
Thanks for the turn around! Let me know when you can get a release out onto PyPi
