### ISSUE TITLE
Green version with Pyre

### ISSUE THREAD

**Issue by tangb** [zeromq/pyzmq#1084]
I'm trying to use Pyre in bottle application and it seems Pyre is not working with green version of PyZMQ (tell me if I'm wrong :smile: ). In any case my app blocks when I run my Pyre thread.

So I tryed to use green pyzmq like explained in [green __init__ file](https://github.com/zeromq/pyzmq/blob/master/zmq/green/__init__.py) replacing all _import zmq_ by _import zmq.green as zmq_ but when I launch my program I always have this kind of exception:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "toto.py", line 56, in run
    node = PyreGevent('TEST')
  File "/usr/local/lib/python3.4/dist-packages/pyre/pyre.py", line 310, in __init__
    self.actor = ZActorGevent(self._ctx, PyreNode, self._outbox)
  File "/usr/local/lib/python3.4/dist-packages/pyre/zactor.py", line 139, in __init__
    self.pipe.wait()
  File "/usr/local/lib/python3.4/dist-packages/pyre/zsocket.py", line 62, in wait
    msg = self.recv()
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 268, in recv
    self._wait_read()
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 175, in _wait_read
    assert self.__readable.ready(), "Only one greenlet can be waiting on this event"
AttributeError: 'NoneType' object has no attribute 'ready'
```

I spent 3 days to test a lot of things without success.
The Pyre ZSocket that inherites from zmq.Socket doesn't call __setup_events function from green Socket like expected. Consequently all class members (__writeable and readable in my case) are None and cannot be called. I really don't understand what is happening :cry:

I already submit an issue in [Pyre project](https://github.com/zeromq/pyre/issues/120).

Please help me :wink:

**Comment by tangb** [comment]
I found the issue, there was problem in super contructor call of zsocket.
