### ISSUE TITLE
zmq hang when delete an zmq context

### ISSUE THREAD

**Issue by zsluedem** [zeromq/pyzmq#1113]
here is my fake code 
```python

import zmq
import zmq.asyncio

zmq.asyncio.install()

websocket = websockets() # an asyncio socket

socket_future = socket.recv()  # return a future

zmq_socket = zmq.context.socket() # a sub zmq socket

zmq_future = zmq_socket.recv_multipart()

dones, pending = await asyncio.wait([zmq_future, socket_future], timeout=PING_INTERVAL,
                                             return_when=asyncio.FIRST_COMPLETED)

do_something_with(dones, pending)

```

descriptions:
I run the code in an loop. Sometimes the code stop running and hang for long.And when the code stop running , i try to *KeyboardInterrupt* and the error below show, it seems zmq cannot delete the context, and stop just right there to prevent my code to run.

this situation seem to happen when the zmq_socket return the message and the websocket close connections at the same time.

```python
Exception ignored in: <bound method Context.__del__ of <zmq.asyncio.Context object at 0x7faa084d06d8>>
Traceback (most recent call last):
  File "/home/jzquant/lenv/lib/python3.6/site-packages/zmq/sugar/context.py", line 46, in __del__
    self.term()
  File "zmq/backend/cython/context.pyx", line 136, in zmq.backend.cython.context.Context.term
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
```

**Comment by zsluedem** [comment]
i am pretty sure the situation happened when the websocket closed unexpectly while the zmq_socket recv message.

**Comment by zsluedem** [comment]
I found the solution now.
It seem like the way i init the zmq context the wrong way.

I checked the source code
```python

cdef class Context:

    cdef object __weakref__     # enable weakref
    cdef void *handle           # The C handle for the underlying zmq object.
    cdef bint _shadow           # whether the Context is a shadow wrapper of another
    cdef void **_sockets        # A C-array containg socket handles
    cdef size_t _n_sockets      # the number of sockets
    cdef size_t _max_sockets    # the size of the _sockets array
    cdef int _pid               # the pid of the process which created me (for fork safety)
    
    cdef public bint closed   # bool property for a closed context.
    cdef inline int _term(self)
    # helpers for events on _sockets in Socket.__cinit__()/close()
    cdef inline void _add_socket(self, void* handle)
    cdef inline void _remove_socket(self, void* handle)
```

the context object hold all the socket handles, but i create  the context every time i create the zmq_socket. So the context should be a global variable.So i just init the context in global way , the problem solved.

**Comment by zsluedem** [comment]
i am going to close it now
