### ISSUE TITLE
DISH socket not working with asyncio context

### ISSUE THREAD

**Issue by dragos-vlad** [zeromq/pyzmq#1139]
Hi,

I'm trying to initialise a DISH socket using `zmq.asyncio.Context` fails with:
```
File "zmq/backend/cython/socket.pyx", line 492, in zmq.backend.cython.socket.Socket.get
server_1  |   File "zmq/backend/cython/socket.pyx", line 264, in zmq.backend.cython.socket._getsockopt
server_1  |   File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
server_1  | zmq.error.ZMQError: Invalid argument
```

The code i'm using is:
```
ctx = zmq.asyncio.Context.instance()
ctx.socket(zmq.DISH)
```

Initialising the socket with `zmq.Context` works as intended. 

System Info:
```
os: Debian 8
python: 3.6.3
pyzmq: 17.0.0.b4
libzmq: 4.2.3
Draft API available: True
```

**Comment by dragos-vlad** [comment]
I'm also getting this exception when the application closes.
```
Exception ignored in: <bound method Socket.__del__ of <zmq.asyncio.Socket object at 0x7f3901bb4e18>>
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/zmq/sugar/socket.py", line 66, in __del__
     self.close()
   File "/usr/local/lib/python3.6/site-packages/zmq/_future.py", line 157, in close
     self._clear_io_state()
   File "/usr/local/lib/python3.6/site-packages/zmq/asyncio/__init__.py", line 60, in _clear_io_state
     self.io_loop.remove_reader(self._fd)
   File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 342, in remove_reader
     return self._remove_reader(fd)
   File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 279, in _remove_reader
     key = self._selector.get_key(fd)
   File "/usr/local/lib/python3.6/selectors.py", line 189, in get_key
     return mapping[fileobj]
   File "/usr/local/lib/python3.6/selectors.py", line 70, in __getitem__
     fd = self._selector._fileobj_lookup(fileobj)
   File "/usr/local/lib/python3.6/selectors.py", line 224, in _fileobj_lookup
     return _fileobj_to_fd(fileobj)
   File "/usr/local/lib/python3.6/selectors.py", line 39, in _fileobj_to_fd
     "{!r}".format(fileobj)) from None
 ValueError: Invalid file object: None
```

**Comment by minrk** [comment]
do DISH sockets not have zmq.FD? If so, then they cannot be used with asyncio.

**Comment by dragos-vlad** [comment]
@minrk How do I find out?

**Comment by minrk** [comment]
Looks like it was an explicit design choice in libzmq to not support ZMQ_FD (https://github.com/zeromq/libzmq/issues/2941) in new threadsafe sockets (server/client, radio/dish, scatter/gather). Until that's fixed, you won't be able to use these sockets with asyncio or tornado. I wouldn't recommend using any of the draft-api sockets in production.

**Comment by dragos-vlad** [comment]
Like you mentioned in the libzmq issue it's pretty important for the final version of the sockets to expose a way for event loops to work with them. Until then I recommend we keep this issue open. 

Thanks for your help.

**Comment by minrk** [comment]
Adding a note to [draft support](https://github.com/zeromq/pyzmq/blob/master/docs/source/draft.rst) that libzmq draft sockets cannot be used with eventloops would be worthwhile. Thanks!

**Comment by smalls12** [comment]
Was poking around with RADIO/DISH and asyncio, stumbled onto this issue.
I've gone through some of the genesis of the problem.
Do we know if this is still an issue in libzmq?

**Comment by alonbl** [comment]
Hi,
It would be very nice if this can be implemented or even some hints of how to implement/what to look into.
Thanks,

**Comment by minrk** [comment]
This is a feature request for libzmq to implement event-loop-supporting handles for sockets. Until they address that, there isn't really anything pyzmq or users can do, other than do blocking calls in background threads. If DISH sockets get ZMQ_FD support, it should work with asyncio without any changes to pyzmq. If they choose to go another way, it might require some code in pyzmq to deal with it. There is a [proposal](https://github.com/zeromq/libzmq/issues/2941#issuecomment-1583576763) that sounds like it would work, to me, but someone has to implement it in libzmq.

**Comment by alonbl** [comment]
Thanks for explaining that @minrk,
I will try to see if there is an open issue at libzmq side and create relationship.

**Comment by alonbl** [comment]
Found: https://github.com/zeromq/libzmq/issues/2941

**Comment by steamraven** [comment]
It appears zmq_poller_fd was added to libzmq as a draft api in 4.3.2.  With this, it should be possible for pyzmq _future code to create a poller, and the shadow socket,  and pull the poller fd to use in the event loop.

**Comment by alonbl** [comment]
> It appears zmq_poller_fd was added to libzmq as a draft api in 4.3.2. With this, it should be possible for pyzmq _future code to create a poller, and the shadow socket, and pull the poller fd to use in the event loop.

oh! right.

```
* New DRAFT (see NEWS for 4.2.0) zmq_poller_fd that returns the FD of a thread
  safe socket. See doc/zmq_poller.txt for details.
```

@minrk this is older than recent replies, is this what required?

**Comment by minrk** [comment]
I believe it may be possible to do that. It is an API that is unfortunately _unique_ to the threadsafe sockets, so there is still no consistent API to get a pollable FD.

I plan to wait for a _stable_ (not draft) API that is consistently supported, since when I've tried to support draft APIs in the past, libzmq has broken pyzmq a number of times. Especially since there appears to be a [concrete proposal](https://github.com/zeromq/libzmq/issues/2941#issuecomment-1583576763) that would make draft sockets work with zmq.asyncio today, without any changes to pyzmq at all.

**Comment by steamraven** [comment]
Is anyone aware of any plans for moving draft to stable?  Its been 9 years.   6 Years since zmq_poller_fd and almost 2 years for that proposal.

The proposal, as outlined, will not work unless you keep track of the signaler and clean it up.  The performance issue mentioned was closed due to user error.

**Comment by minrk** [comment]
closed by experimental support added in #2103
