### ISSUE TITLE
Python interpreter blocks at exit when zmq.Again raised

### ISSUE THREAD

**Issue by CharlesB2** [zeromq/pyzmq#1144]
When using a REQ socket with a receive timeout, if the recv() times out, the interpreter is blocked at exit, and has to be interrupted with ctrl-C.

The issue happens with 17.0 and 16.0.4.
```
>>> import zmq
>>> context = zmq.Context()
>>> s=context.socket(zmq.REQ)
>>> s.setsockopt(zmq.RCVTIMEO, 500)
>>> s.connect("ipc:///tmp/inexistant")
>>> s.send(b"hello")
>>> s.recv()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "zmq/backend/cython/socket.pyx", line 790, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 826, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 193, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/socket.pyx", line 188, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable
>>> quit()
[BLOCKINGHERE]
^C
```

Here is the output when exiting an IPython session, since it gives better stack trace in the `atexit` function, but it is the same behaviour with python.
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/charles/prog/vserver/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3256, in atexit_operations
    self.reset(new_session=False)
  File "/home/charles/prog/vserver/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 1236, in reset
    del ns[k]
KeyboardInterrupt
```

```
Python-3.6.3 (default, Oct  3 2017, 21:45:48)
[GCC 7.2.0]
pyzmq-17.0.0
libzmq-4.1.6
```

**Comment by CharlesB2** [comment]
Problem raised here: https://stackoverflow.com/q/44273941/11343, found the solution

> A default value of the LINGER attribute forces the socket instance to wait upon an attempt to .close()
`
socket.setsockopt( zmq.LINGER,      0 )`
