### ISSUE TITLE
pyzmq_stream_poller.py example fails to run with v16.0.2

### ISSUE THREAD

**Issue by rmackinnon** [zeromq/pyzmq#1158]
Greetings,

I took the example off [Readthedocs](http://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/multisocket/tornadoeventloop.html) and found the example fails to run.

#### Expected Result:
To complete and run example.

#### Actual Result:
```Traceback (most recent call last):
  File "/home/user/tests/pyzmq_stream_poller.py", line 8, in <module>
    ioloop.install()
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
```

#### Comments:
While ZMQIOLoop class does have the method ```initialize```, seems the reference to ```initialized``` is in error. If my assumption this is a typo, I'm happy to put together a PR for you.

#### Running Environment:
libzmq-4.2.3
pyzmq-16.0.2
Python-2.7.14 (default, Jan 28 2018, 14:32:44) 
[GCC 6.4.0]

**Comment by rmackinnon** [comment]
I dug through my pip and repo manager and found it wasn't showing the latest version (17.x), short story short: clone/build/install of current master builds and the example code runs fine.  Closing this out.
