### ISSUE TITLE
Error thrown by call_later()

### ISSUE THREAD

**Issue by ealione** [zeromq/pyzmq#1169]
I am getting the following error thrown when I try to delay the call of a function

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 1209, in _run
    return self.callback()
  File "/home/pi/test.py", line 123, in _tick
    self._delayed_cb = IOLoop.call_later(self._create_stream, 5000)
TypeError: unbound method call_later() must be called with ZMQIOLoop instance as first argument (got instancemethod instance instead)
```

The code causing this issue is the following:

```
self._delayed_cb = IOLoop.call_later(self._create_stream, 5000)
self._delayed_cb.start()
```

Has something changed in the way call_later works, or is it something I am doing wrong?

**Comment by minrk** [comment]
`call_later` is an instance method, not a class method. You would use it after getting the current loop, e.g.:

```python
IOLoop.current().call_later(2, func)
```
