### ISSUE TITLE
TypeError when sending bytebuffer using PyPy-3.5.3 v6.0.0

### ISSUE THREAD

**Issue by jean-airoldie** [zeromq/pyzmq#1212]
Hi,
I am unable to send a bytebuffer from a PUSH socket using pypy3.
The code was ran using `virtualenv -p pypy3`, and a [pypy3 linux x86-64 prebuilt binary](https://www.pypy.org/download.html).

Here are my libraries version:
```
libzmq-4.2.3
pyzmq-17.1.0
PyPy-3.5.3 (fdd60ed87e94, Apr 24 2018, 06:10:04)
[PyPy 6.0.0 with GCC 6.2.0 20160901]
```
Here is my system info :
(Note that Running this code from the [pypy3-6.0.0 image](https://hub.docker.com/_/pypy/) yields the same issue.)
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
Here is the a minimum amount of code to reproduce this issue :

```python3
#!/usr/bin/env pypy3

# filename : push.py

import zmq

ctx = zmq.Context()
push = ctx.socket(zmq.PUSH)
push.bind("tcp://*:3001")

buf = bytearray(b'\x00')

push.send(buf)
```

Traceback :
```
  Traceback (most recent call last):
  File "./push.py", line 13, in <module>
    push.send(buf)
  File "/home/maxence/lumby/lumby-storage/ENV/site-packages/zmq/sugar/socket.py", line 392, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "/home/maxence/lumby/lumby-storage/ENV/site-packages/zmq/backend/cffi/socket.py", line 209, in send
    c_message = ffi.new('char[]', message)
  File "/home/maxence/sources/pypy3-v6.0.0-linux64/lib_pypy/cffi/api.py", line 258, in new
    return self._backend.newp(cdecl, init)
TypeError: expected new array length or list/tuple/str, not bytearray
```

**Comment by minrk** [comment]
thanks for the report! should be fixed by #1216
