### ISSUE TITLE
zmq multiprocessing start fail on windows

### ISSUE THREAD

**Issue by rilcky** [zeromq/pyzmq#1284]
I have a problem with zmq multiprocessing, the code below works well on linux but fails on windows, zmq 4.2.5, python 2.7,

```
from multiprocessing import Process
from multiprocessing import Queue
class MessageHandler(Process):
    def init(self, zmq_context, msg_queue, zmq_url):
        super(MessageHandler, self).init()
        self.queue = msg_queue
        self.context = zmq_context
        self.url = zmq_url
    def run(self):
        self.sub = self.context.socket(zmq.SUB)
        self.sub.connect(self.url)
        self.sub.setsockopt(zmq.SUBSCRIBE, b'')
        while True:
            msg = self.sub.recv()
        self.queue.put_nowait(msg)
md_context = zmq.Context()
md_queue = Queue()
md_url = "tcp//192.168.1.201:9995"
md_handler = MessageHandler(md_context, md_queue, md_url)
md_handler.start()

```
Assert error as below:
```

Traceback (most recent call last):
File "C:/Code/achilles_recv.py", line 214, in 
instance = SimpleStrategy()
File "C:/Code/achilles_recv.py", line 69, in init
StrategyBase.init(self, self.process_id)
File "C:\Code\base\StrategyBase.py", line 67, in `init`
self.init_connections()
File "C:\Code\engine\StrategyEngine.py", line 43, in init_connections
md_handler.start()
File "C:\ProgramData\Anaconda2\lib\multiprocessing\process.py", line 130, in start
self._popen = Popen(self)
File "C:\ProgramData\Anaconda2\lib\multiprocessing\forking.py", line 277, in init
dump(process_obj, to_child, HIGHEST_PROTOCOL)
File "C:\ProgramData\Anaconda2\lib\multiprocessing\forking.py", line 199, in dump
ForkingPickler(file, protocol).dump(obj)
File "C:\ProgramData\Anaconda2\lib\pickle.py", line 224, in dump
self.save(obj)
File "C:\ProgramData\Anaconda2\lib\pickle.py", line 331, in save
self.save_reduce(obj=obj, *rv)
File "C:\ProgramData\Anaconda2\lib\pickle.py", line 425, in save_reduce
save(state)
File "C:\ProgramData\Anaconda2\lib\pickle.py", line 286, in save
f(self, obj) # Call unbound method with explicit self
File "C:\ProgramData\Anaconda2\lib\pickle.py", line 655, in save_dict
self._batch_setitems(obj.iteritems())
File "C:\ProgramData\Anaconda2\lib\pickle.py", line 687, in _batch_setitems
save(v)
File "C:\ProgramData\Anaconda2\lib\pickle.py", line 306, in save
rv = reduce(self.proto)
File "stringsource", line 2, in zmq.backend.cython.context.Context.reduce_cython
TypeError: no default reduce due to non-trivial cinit

```
debug to find that zmq packege has not a function of "reduce"， could anyone help with this issue?

**Comment by minrk** [comment]
`__init__` is run in the parent process, while `run` is in the subprocess. zmq sockets and contexts cannot be passed from one process to the next. Make sure to create a new Context in `run` and you might have more success.

**Comment by rilcky** [comment]
Wow, it works! Thanks a lot!
