### ISSUE TITLE
Error during pip install py-zmq-pipeline

### ISSUE THREAD

**Issue by aks1981** [zeromq/pyzmq#1289]
Hi team,

I am getting below error during ip install py-zmq-pipeline installation. Kindly help me.
I am following  https://py-zmq-pipeline.readthedocs.io/en/latest/installation.html

libzmq-4.3.1
pyzmq-18.0.1
Python-3.7.3 (default, May 16 2019, 15:54:12) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

ERROR:

(test) [root@jumpbox-sit test]# **pip install py-zmq-pipeline**
Collecting py-zmq-pipeline
  Using cached https://files.pythonhosted.org/packages/6b/db/1229cfb3461e47517cca3af2b4e508c74ebf6bcdad0cfad9d0a106f047e5/py-zmq-pipeline-0.1.7.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/py_zmq_pipeline.egg-info
    writing pip-egg-info/py_zmq_pipeline.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ovrh49g6/py-zmq-pipeline/setup.py", line 57, in <module>
        "Topic :: Software Development :: Libraries :: Python Modules",
      File "/root/test/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/src/Python-3.7.3/Lib/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/src/Python-3.7.3/Lib/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/src/Python-3.7.3/Lib/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/root/test/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 289, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/root/test/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 621, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/src/Python-3.7.3/Lib/distutils/dist.py", line 1117, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/root/test/lib/python3.7/site-packages/setuptools/dist.py", line 168, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/usr/src/Python-3.7.3/Lib/distutils/util.py", line 464, in rfc822_escape
        lines = header.split('\n')
    TypeError: a bytes-like object is required, not 'str'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ovrh49g6/py-zmq-pipeline/
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test) [root@jumpbox-sit test]# deactivate

**Comment by minrk** [comment]
This repo is for pyzmq, but the reported issue is for py-zmq-pipeline, which is a different package. I'd recommend finding the repo for that project.
