### ISSUE TITLE
recv_json hangs inside pytest environment

### ISSUE THREAD

**Issue by JulianRMedina** [zeromq/pyzmq#1319]
Python: 3.6
pyzmq: 17.1.2, this same issue occurs on pyzmq 18.2.0.dev0 or current master
I'm trying to use a pytest fixture to create push and poll sockets. Like so:

```
@pytest.fixture(scope="function")
def mock_zmq_push_pull():
    """
    Pytest fixture for generating a zmq PULL socket.

    :return: A zmq PULL socket which messages can be pulled from.
    """

    bind_connection_pull_point = "tcp://127.0.0.1:3003"
    bind_connection_push_point = "tcp://127.0.0.1:3003"

    # Generate zmq context
    context = zmq.Context()

    # zmq.PUSH/PULL are recommended from pyzmq docs. Pylint believes this
    # is incorrect
    push_connection = context.socket(zmq.PUSH)  # pylint: disable=no-member
    push_connection.connect(bind_connection_push_point)
    pull_connection = context.socket(zmq.PULL)  # pylint: disable=no-member
    pull_connection.connect(bind_connection_pull_point)

    # Allow time for connections to start
    time.sleep(0.15)

    # Yield connection
    yield (push_connection, pull_connection)

    # Close the context and all associated sockets
    context.destroy()
```

Then, when I go to use them in a simple example, the recv_json() of the pull hangs forever:

```
def test_get_gui_connection_push(mock_zmq_push_pull):
    """
    Test that get_gui_connection can create a push connection, send messages, 
    and have them recieved by a pull connection.

    :param mock_zmq_pull: mock zmq PULL socket that can listen for messages
    """

    send_data = {"key-1": "data-1"}

    # Use push_connection to send a simple json object
    mock_zmq_push_pull[0].send_json(send_data)

    # Check that mock pull connection recieved the object
    recvd_data = mock_zmq_push_pull[1].recv_json()

    assert recvd_data == send_data
```

ZMQ stacktrace shows the following when keyboard interrupted:

```
zmq/backend/cython/checkrc.pxd:12: KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/pytest.py", line 102, in <module>
    raise SystemExit(pytest.main())
  File "/usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py", line 74, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 250, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 243, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.6/site-packages/_pytest/terminal.py", line 649, in pytest_sessionfinish
    outcome.get_result()
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 67, in pytest_sessionfinish
    session._setupstate.teardown_all()
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 320, in teardown_all
    self._pop_and_teardown()
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 291, in _pop_and_teardown
    self._teardown_with_finalization(colitem)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 310, in _teardown_with_finalization
    self._callfinalizers(colitem)
  File "/usr/local/lib/python3.6/site-packages/_pytest/runner.py", line 299, in _callfinalizers
    fin()
  File "/usr/local/lib/python3.6/site-packages/_pytest/fixtures.py", line 847, in finish
    raise val.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/_pytest/fixtures.py", line 840, in finish
    func()
  File "/usr/local/lib/python3.6/site-packages/_pytest/fixtures.py", line 791, in _teardown_yield_fixture
    next(it)
  File "/root/space_roulette_astro/tests/conftest.py", line 206, in mock_zmq_push_pull
    context.destroy()
  File "zmq/backend/cython/context.pyx", line 244, in zmq.backend.cython.context.Context.destroy
  File "zmq/backend/cython/context.pyx", line 136, in zmq.backend.cython.context.Context.term
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt
```
If I remove the context.destroy(), it shows that the code was interupted in recv_json()

```
    def recv_json(self, flags=0, **kwargs):
        """Receive a Python object as a message using json to serialize.
    
        Keyword arguments are passed on to json.loads
    
        Parameters
        ----------
        flags : int
            Any valid flags for :func:`Socket.recv`.
    
        Returns
        -------
        obj : Python object
            The Python object that arrives as a message.
    
        Raises
        ------
        ZMQError
            for any of the reasons :func:`~Socket.recv` might fail
        """
>       msg = self.recv(flags)

/usr/local/lib64/python3.6/site-packages/zmq/sugar/socket.py:665: 
```

**Comment by JulianRMedina** [comment]
The issue here was that on the push socket I was using .connect(address) rather than .bind(address)
