### ISSUE TITLE
How to work with `from . import ...` in __init__.py?

### ISSUE THREAD

**Issue by kovkev** [zeromq/pyzmq#1341]
https://github.com/zeromq/pyzmq/blob/ceaf9781717636d408c2f13d444db487ba642ef7/zmq/backend/cython/__init__.py#L6

Hi contributors to pyzmq and thanks tons for your work!!

I found that I cannot impotr `zmq` in my docker container. It seems like all the dependencies are present. I actually see:
```
>>> import zmq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/analysis/thinking/jupyter.binary.runfiles/pypi__pyzmq_18_1_0/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/app/analysis/thinking/jupyter.binary.runfiles/pypi__pyzmq_18_1_0/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/app/analysis/thinking/jupyter.binary.runfiles/pypi__pyzmq_18_1_0/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/app/analysis/thinking/jupyter.binary.runfiles/pypi__pyzmq_18_1_0/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/app/analysis/thinking/jupyter.binary.runfiles/pypi__pyzmq_18_1_0/zmq/backend/select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/app/analysis/thinking/jupyter.binary.runfiles/pypi__pyzmq_18_1_0/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
```

I'm very confused, as there's not much more information. 

However, I thought about how imports work and maybe this is creating a loop? When we do `from . import ...` inside of a __init__.py, Python's import system might be trying to run __init__.py yet again?

How do we deal with that?

I found two questions on SO about this but I don't know what to make of it... how helpful is it?

https://stackoverflow.com/questions/31128333/python-import-class-in-init-py-from-file-in-same-package

https://stackoverflow.com/questions/42862042/in-python-how-to-import-from-the-init-py-in-the-same-directory

**Comment by haverins** [comment]
What does your Dockerfile look like? I'm installing pyzmq via pip and I have no problems.

**Comment by minrk** [comment]
This error is a result of pyzmq not building or installing correctly, so it's likely down to how it was installed. As mentioned above, showing the Dockerfile or other code used to install pyzmq would help.

**Comment by kovkev** [comment]
I found out that using the right python version was important. My host and my container need to run the same python version. I'm not sure why. I wish pyzmq could detect that and the version might be different and issue an error message accordingly.

**Comment by minrk** [comment]
This error message should be improved by 70a5d41217d344c4914123e3758b88dd88994026
