### ISSUE TITLE
Exception ignored in: ... __del__ - close - _rm_socket 

### ISSUE THREAD

**Issue by walnutgeek** [zeromq/pyzmq#1356]
After running pytest see this message repeating twice:

Exception ignored in: <function Socket.__del__ at 0x7f83905c59e0>
Traceback (most recent call last):
  File "/Users/wg/miniconda3/envs/abv/lib/python3.7/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/Users/wg/miniconda3/envs/abc/lib/python3.7/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/Users/wg/miniconda3/envs/abc/lib/python3.7/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable

All test passed and pytest returns 0. (macos, python 3.7.6)

Seem not hurt anything, but would be nice to why? GC collects something more then once? Any way to suppress?

**Comment by minrk** [comment]
What version of pyzmq? Are you running pytest in this repo, or for another package?

This error occurs because of randomized order in garbage collection on more recent versions of Python. Just about anything can be None at process teardown time, ~regardless of reference order, so literally all attribute access must check for None in `__del__`. I thought I had dealt with this, though, but maybe there's a case I missed if you are seeing this with the latest pyzmq

**Comment by walnutgeek** [comment]
Yup, that would hard to track, when you cannot trust state of any variable. 

pyzmq I am using is 18.1.1. Pytest run is from closed source project.

**Comment by lvxejay** [comment]
I've noticed this exact same behavior in my projects as well
```
Exception ignored in: <function Socket.__del__ at 0x7f19fffc7560>
Traceback (most recent call last):
  File "/home/jmw/.pyenv/versions/3.7.4/lib/python3.7/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/home/jmw/.pyenv/versions/3.7.4/lib/python3.7/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/home/jmw/.pyenv/versions/3.7.4/lib/python3.7/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Exception ignored in: <function Socket.__del__ at 0x7f19fffc7560>
Traceback (most recent call last):
  File "/home/jmw/.pyenv/versions/3.7.4/lib/python3.7/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/home/jmw/.pyenv/versions/3.7.4/lib/python3.7/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/home/jmw/.pyenv/versions/3.7.4/lib/python3.7/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Exception ignored in: <function Socket.__del__ at 0x7f19fffc7560>
Traceback (most recent call last):
  File "/home/jmw/.pyenv/versions/3.7.4/lib/python3.7/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/home/jmw/.pyenv/versions/3.7.4/lib/python3.7/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/home/jmw/.pyenv/versions/3.7.4/lib/python3.7/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
```
Not sure what's causing it.

**Comment by minrk** [comment]
Thanks for the traceback! I'm pretty sure #1367 will fix it. Can you apply that patch and confirm?

**Comment by lvxejay** [comment]
Based on my testing, this seems to work. I will say though, I think this patch is also introducing some other positive side effects, where I'm seeing more _consistent_ behavior from pyzmq. I'm using pyzmq in a relatively unorthodox python runtime environment. I have one shared zmq context for the threaded part of my application, a different context for a script I'm running as a subprocess, and I also have some multiprocessing going on. Generally, things seem more stable. and I haven't seen the garbage collection issue pop back up yet.

**Comment by chathika** [comment]
#1367 fixed this issue for me. Any idea when this fix will be included in a release @minrk ? 
I've had the above issue when using [scoop](https://scoop.readthedocs.io/en/latest/index.html) for [DEAP](https://github.com/DEAP/deap). Reverting to pyzmq 18.0.0 helped resolve the garbage collection issues for now.
