### ISSUE TITLE
AttributeError: module 'pickle' has no attribute 'DEFAULT_PROTOCOL'

### ISSUE THREAD

**Issue by johentsch** [zeromq/pyzmq#1428]
Hello folks,

I think my problem is a very peculiar one and I am not sure whether the problem lies in zmq, but at least the error occurs there.

The story goes like this: I was coding in Atom using iPykernels. Specifically, I was trying to pickle a difficult object with `dill` and `pickle` modules, simply applying the method `dumps()`. The objects had unpicklable objects so the kernel died several times and I had to restart it. But at some point it did not restart, instead, with every trial, I got this:
```
Traceback (most recent call last):
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/zmq/sugar/socket.py", line 38, in <module>
    DEFAULT_PROTOCOL = pickle.DEFAULT_PROTOCOL
AttributeError: module 'pickle' has no attribute 'DEFAULT_PROTOCOL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hentsche/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hentsche/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/ipykernel/connect.py", line 18, in <module>
    import jupyter_client
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/zmq/__init__.py", line 49, in <module>
    from zmq import sugar
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/zmq/sugar/__init__.py", line 7, in <module>
    from zmq.sugar import (
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/zmq/sugar/context.py", line 20, in <module>
    from .socket import Socket
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/zmq/sugar/socket.py", line 40, in <module>
    DEFAULT_PROTOCOL = pickle.HIGHEST_PROTOCOL
```

But what is even more surprising: That happened on my old Anaconda installation with Python 3.7 (same error, just with python3.7 in the path): That one I have removed completely and installed a completely fresh Anaconda with Python 3.8. The problem persisted in Atom, so I fired up my Jupyter Lab and here comes the best part: One of my existing notebooks works as usual, but any other - including a completely new one - does not manage to start a kernel and the error message is the same! I have also tried with a new kernel in a new conda environment.

Let me know if more information is needed and thanks for your help.

EDIT: I have [filed the same report to ipykernel](https://github.com/ipython/ipykernel/issues/549).

**Comment by johentsch** [comment]
Simple solution: There are a lot of things in the `tmp` folder, also a file called `pickle.py`. That's what was causing all the trouble...

**Comment by jeff-hykin** [comment]
so glad you posted this, I just ran into the exact same issue and had no idea what was going on. I think this is an issue with the python import system

**Comment by minrk** [comment]
> I think this is an issue with the python import system

I agree! I've long thought that PYTHONPATH and friends should come after the stdlib, but before site-packages, but I don't think there is hope of it changing.
