### ISSUE TITLE
error with zmq_poll()

### ISSUE THREAD

**Issue by xiongma** [zeromq/pyzmq#1434]
I don't know the exact error, here is the full error trackback
```
Process gateway:
Process bert-0:
Traceback (most recent call last):
  File "/home/cally/softwares/pycharm-2018.3.7/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 621, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "/home/cally/softwares/pycharm-2018.3.7/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 125, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "/home/cally/softwares/pycharm-2018.3.7/helpers/pydev/pydevd.py", line 877, in do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
Process bert-head:
Traceback (most recent call last):
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/pea.py", line 85, in run
    self.loop_body()
Traceback (most recent call last):
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/pea.py", line 112, in loop_body
    msg = self.zmqlet.recv_message(callback=self.msg_callback)
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/zmq.py", line 89, in recv_message
    i_sock = self._pull()
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/zmq.py", line 113, in _pull
    return self.out_sock
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/zmq.py", line 113, in _pull
    return self.out_sock
  File "/home/cally/softwares/pycharm-2018.3.7/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 621, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
Traceback (most recent call last):
  File "/home/cally/softwares/pycharm-2018.3.7/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 125, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "/home/cally/softwares/pycharm-2018.3.7/helpers/pydev/pydevd.py", line 877, in do_wait_suspend
    time.sleep(0.01)
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/pea.py", line 85, in run
    self.loop_body()
Process bert-1:
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/pea.py", line 112, in loop_body
    msg = self.zmqlet.recv_message(callback=self.msg_callback)
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/zmq.py", line 89, in recv_message
    i_sock = self._pull()
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/zmq.py", line 109, in _pull
    socks = dict(self.poller.poll(interval))
Traceback (most recent call last):
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/site-packages/zmq/sugar/poll.py", line 103, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/pea.py", line 85, in run
    self.loop_body()
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
Process bert-tail:
KeyboardInterrupt
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/pea.py", line 112, in loop_body
    msg = self.zmqlet.recv_message(callback=self.msg_callback)
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/zmq.py", line 89, in recv_message
    i_sock = self._pull()
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/zmq.py", line 109, in _pull
    socks = dict(self.poller.poll(interval))
Traceback (most recent call last):
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/site-packages/zmq/sugar/poll.py", line 103, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/pea.py", line 85, in run
    self.loop_body()
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/pea.py", line 85, in run
    self.loop_body()
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/gateway.py", line 133, in loop_body
    self.io_loop.start()
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/pea.py", line 112, in loop_body
    msg = self.zmqlet.recv_message(callback=self.msg_callback)
KeyboardInterrupt
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/zmq.py", line 89, in recv_message
    i_sock = self._pull()
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/zmq.py", line 109, in _pull
    socks = dict(self.poller.poll(interval))
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/asyncio/base_events.py", line 1750, in _run_once
    event_list = self._selector.select(timeout)
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/site-packages/zmq/sugar/poll.py", line 103, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll
KeyboardInterrupt
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

**Comment by kinow** [comment]
No code to reproduce it @xiongma ?

**Comment by xiongma** [comment]
sry about the long traceback, the code is too sophisticated and can't be reproduced, sry again.

**Comment by xiongma** [comment]
Does it seem like this error due to the loop event? @kinow

**Comment by kinow** [comment]
> sry about the long traceback, the code is too sophisticated and can't be reproduced, sry again.

Gotcha, maybe someone else will be able to guess what could be wrong here, though it runs the risk of being close if no one is able to reproduce the issue :+1:

**Comment by kinow** [comment]
> Does it seem like this error due to the loop event? @kinow

Sorry, I can't really tell. I could only see that it apparently was running in PyCharm, maybe in debug mode, and also see some of the modules involved. But it's hard for me to understand how I would reproduce, fix, and try to write a unit test to prevent it from happening again.

But maybe somebody else will have had a similar issue and be able to help :-)

**Comment by xiongma** [comment]
```
  File "/home/cally/Awake/Code/bert2tf/bert2tf/peapods/zmq.py", line 109, in _pull
    socks = dict(self.poller.poll(interval))
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/asyncio/base_events.py", line 1750, in _run_once
    event_list = self._selector.select(timeout)
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/site-packages/zmq/sugar/poll.py", line 103, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll
KeyboardInterrupt
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/cally/.pyenv/versions/3.7.7/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```
this is the main reason for this error, didn't I?
I guess the error came from `zmq_poll()`, but I can't debug due to the code was written by cpython

**Comment by kinow** [comment]
I guess you could use `strace` or some other tool to look what is going on. Did it hang and then you had to stop it, causing a `KeyboardInterrupt`?

**Comment by xiongma** [comment]
solved

**Comment by kinow** [comment]
> solved

Did you figure out what was the problem @xiongma ? Is it something that could happen to other users? (if so, could you share :grimacing: )

**Comment by xiongma** [comment]
it's my code logic problem not `pyzmq`, sry to bother you!

**Comment by kinow** [comment]
Not a problem @xiongma ! Glad it worked in the end :+1:
