### ISSUE TITLE
pyzmq 22 on Windows conda Python 3.8 fails to load

### ISSUE THREAD

**Issue by QuLogic** [zeromq/pyzmq#1496]
See latest [Matplotlib build on AppVeyor](https://ci.appveyor.com/project/matplotlib/matplotlib/builds/37500078/job/thw862fcje2xqw1c):
```
Traceback (most recent call last):
  File "c:\miniconda37-x64\envs\test-environment\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\miniconda37-x64\envs\test-environment\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda37-x64\envs\test-environment\Scripts\jupyter-nbconvert.EXE\__main__.py", line 4, in <module>
  File "c:\miniconda37-x64\envs\test-environment\lib\site-packages\nbconvert\__init__.py", line 4, in <module>
    from .exporters import *
  File "c:\miniconda37-x64\envs\test-environment\lib\site-packages\nbconvert\exporters\__init__.py", line 4, in <module>
    from .slides import SlidesExporter
  File "c:\miniconda37-x64\envs\test-environment\lib\site-packages\nbconvert\exporters\slides.py", line 12, in <module>
    from ..preprocessors.base import Preprocessor
  File "c:\miniconda37-x64\envs\test-environment\lib\site-packages\nbconvert\preprocessors\__init__.py", line 10, in <module>
    from .execute import ExecutePreprocessor
  File "c:\miniconda37-x64\envs\test-environment\lib\site-packages\nbconvert\preprocessors\execute.py", line 8, in <module>
    from nbclient import NotebookClient, execute as _execute
  File "c:\miniconda37-x64\envs\test-environment\lib\site-packages\nbclient\__init__.py", line 3, in <module>
    from .client import NotebookClient, execute  # noqa: F401
  File "c:\miniconda37-x64\envs\test-environment\lib\site-packages\nbclient\client.py", line 21, in <module>
    from jupyter_client import KernelManager
  File "c:\miniconda37-x64\envs\test-environment\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "c:\miniconda37-x64\envs\test-environment\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "c:\miniconda37-x64\envs\test-environment\lib\site-packages\zmq\__init__.py", line 84, in <module>
    from zmq import backend
  File "c:\miniconda37-x64\envs\test-environment\lib\site-packages\zmq\backend\__init__.py", line 32, in <module>
    raise original_error from None
  File "c:\miniconda37-x64\envs\test-environment\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "c:\miniconda37-x64\envs\test-environment\lib\site-packages\zmq\backend\select.py", line 32, in select_backend
    mod = import_module(name)
  File "c:\miniconda37-x64\envs\test-environment\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\miniconda37-x64\envs\test-environment\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed while importing error: The specified module could not be found.
```

**Comment by minrk** [comment]
Thank you for testing and sorry for the trouble!

This is unbelievably maddening. I truly don't understand what is going on with Windows builds not being portable to *some* environments, but always working on all my test VMs. It seems impossible to verify or diagnose. I'm this close to revoking all Windows wheels and telling Windows users to use conda if they don't want to compile from source. I've lost *weeks* of time to this nonsense.

Do pyzmq 21 and/or 20  work?

**Comment by minrk** [comment]
I've reproduced this on my VM and it seems to be specific to conda. The wheels work fine with Python.org Python. I'll flail around in the dark a bit longer to see why conda Python is different from Python.org on the same system in terms of DLL support.

**Comment by QuLogic** [comment]
Yes, 21.0.z (z != 0) worked, as did 20.
