### ISSUE TITLE
Compilation From Source Failed

### ISSUE THREAD

**Issue by rachha** [zeromq/pyzmq#1539]
OS: alpine 3.13
libzmq: 4.3.4
pyzmq: 19.0.2

libzmq build:

```
/configure --prefix=/libzmq/build_static_pic --without-docs --enable-static=yes --enable-shared=no --with-pic
make 
make install
```

Pyzmq build:

`python3 setup.py configure --zmq=/libzmq/build_static_pic`

error: 
`python3 setup.py configure --zmq=/libzmq/build_static_pic`

the complete log is attached as a file
[pyzmq_error.txt](https://github.com/zeromq/pyzmq/files/6545056/pyzmq_error.txt)

tried with pyzmq 22.0.0 also got same error

**Comment by minrk** [comment]
I haven't tried to statically link libzmq, but it looks like it has chosen to exclude stdc++ (I can't say whether that's the right thing to do or not, but since it expresses itself as a purely C library, it seems wrong to me).

Try with this `setup.cfg` in the root of the pyzmq directory:

```ini
[global]
zmq_prefix = /libzmq/build_static_pic
skip_check_zmq = True # skip check due to missing transitive libzmq dependency

[build_ext]
# static libzmq means it's missing dependencies,
# add them here
libraries = stdc++ pthread
```

It's possible there are some flags you want to add to building libzmq to tell it to link its dependencies, I'm not sure.

**Comment by rachha** [comment]
Thanks @minrk , the setip.cfg worked. I even build the libzmq with -lstdc++ as LIBS flag, still I get same errors when I'm building pyzmq, will try and update if I find any.

Still using setup.cfg, when I did `ldd  xxx.so` on all the so files it created some of the symbols are not defined. This is the same case even when I build pyzmq with dynamically linked libzmq.


```
ldd ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so
	/lib/ld-musl-x86_64.so.1 (0x7f07d91e8000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f07d8f93000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f07d8f79000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f07d91e8000)
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyUnicode_FromFormat: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyList_New: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyDict_SetItemString: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyDict_Size: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyObject_ClearWeakRefs: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: _PyThreadState_UncheckedGet: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyModuleDef_Init: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyFrame_New: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyObject_GetAttrString: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyImport_AddModule: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyBytes_FromStringAndSize: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyObject_SetAttrString: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyErr_WarnEx: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: _Py_Dealloc: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyModule_NewObject: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyObject_GC_Del: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyCode_New: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyImport_GetModuleDict: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyObject_GC_Track: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyErr_SetString: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyMethod_New: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: _PyObject_GC_New: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyInterpreterState_GetID: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyTuple_GetItem: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyMem_Realloc: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyErr_ExceptionMatches: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyOS_snprintf: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyTraceBack_Here: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyObject_Not: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyObject_Free: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyType_Ready: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyLong_FromLong: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyErr_Clear: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyTuple_New: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyThreadState_Get: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyObject_SetAttr: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyErr_Occurred: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyLong_AsLong: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: _PyDict_GetItem_KnownHash: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyTuple_GetSlice: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyDict_GetItemString: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyObject_Hash: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyDict_New: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: _PyObject_GetDictPtr: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyUnicode_FromString: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyUnicode_InternFromString: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyDict_SetItem: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyUnicode_Decode: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyErr_Format: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyUnicode_FromStringAndSize: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyModule_GetDict: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyObject_GetAttr: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyMem_Malloc: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyErr_WarnFormat: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyTuple_Pack: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: Py_GetVersion: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyObject_GC_UnTrack: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyExc_SystemError: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyExc_RuntimeError: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyExc_DeprecationWarning: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyExc_TypeError: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: _Py_FalseStruct: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyExc_OverflowError: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: _Py_NoneStruct: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: _Py_TrueStruct: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyLong_Type: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyExc_ImportError: symbol not found
Error relocating ./build/lib.linux-x86_64-3.8/zmq/backend/cython/error.cpython-38-x86_64-linux-gnu.so: PyExc_AttributeError: symbol not found
```

**Comment by minrk** [comment]
Does `import zmq` work, though? Those symbols are loaded by the Python interpreter, and aren't generally expected to be defined in Extensions. Linking libpython would define them, but that's not what extensions typically do (this behavior is governed by Python itself, not Extension configuration) because it can result in duplicate interpreter state depending on how Python itself links libpython, and it's not necessary for the symbols to be available.

Building with this dockerfile (and the above setup.cfg) results in working pyzmq against libzmq built as you specified:

```dockerfile
FROM alpine:3.13
RUN apk add g++ make python3-dev
ARG ZMQ=4.3.4
RUN wget https://github.com/zeromq/libzmq/releases/download/v${ZMQ}/zeromq-${ZMQ}.tar.gz \
 && tar -xzf zeromq-${ZMQ}.tar.gz
RUN cd zeromq-${ZMQ} \
 && ./configure --prefix=/libzmq/build_static_pic --without-docs --enable-static=yes --enable-shared=no --with-pic \
 && make -j4 \
 && make install
RUN apk add py3-pip
ARG PYZMQ=22.0.3
RUN pip download pyzmq==$PYZMQ \
 && tar -xzf pyzmq-$PYZMQ.tar.gz
COPY setup.cfg pyzmq-$PYZMQ/setup.cfg  # from above snippet
RUN pip install -vv --no-deps ./pyzmq-$PYZMQ
```

Can I ask more about why you are using a static libzmq, though? It significantly increases the install size of pyzmq because pyzmq has several extensions that each link libzmq, when bundling dynamic libraries using [auditwheel](https://github.com/pypa/auditwheel) also solves single-file portability.

**Comment by rachha** [comment]
no, `import zmq` shows following errror

```
>>> import zmq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pyzmq/pyzmq-19.0.2/zmq/__init__.py", line 50, in <module>
    from zmq import backend
  File "/pyzmq/pyzmq-19.0.2/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/pyzmq/pyzmq-19.0.2/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/pyzmq/pyzmq-19.0.2/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/pyzmq/pyzmq-19.0.2/zmq/backend/select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/pyzmq/pyzmq-19.0.2/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (/pyzmq/pyzmq-19.0.2/zmq/backend/cython/__init__.py)
```
Earlier we are shipping build pyzmq(statically linked libzmq) as dependency to our product, now I'm updating them with newer versions, The reason for which I'm thinking is because of [licensing](https://github.com/zeromq/pyzmq/commit/37295cf2bf267663b04ba77568b729d1dc9964bc).

Now I tried linking libzmq dynamically to puzmq also, able to `pyhton3 configure and python3 build` successfully. 
but `import zmq` fails with the same error as above. When I check *.so files also, those symbols are not found

**Comment by minrk** [comment]
> The reason for which I'm thinking is because of licensing.

Licensing is unaffected by static or dynamic linking. The clause you linked is meant as an explicit clarification of that fact, rather than a differentiator. Some folks argue that static linking applies GPL-like transfer when using an LGPL library (which I think is silly). ZeroMQ has an explicit exception declaring that static linking does not automatically make an executable a 'derivative work' for licensing purposes, so static & dynamic linking are considered equivalent, meant to avoid that ambiguity.

> when I checked those python symbols are not found

Those symbols *should not* be found, and their absence is not an indication of a problem. Checking with `ldd` doesn't tell you if things will work or not, but it can help figure out why *if* they don't work. It is not meaningful to check before you verify that it doesn't work, because the loader may be loading the symbols another way, as is the case for Python extensions. So if it imports, there isn't a problem here.
