### ISSUE TITLE
22.2.1: issue with building documentation

### ISSUE THREAD

**Issue by kloczek** [zeromq/pyzmq#1621]
Just tested that PR and I'm still not able to build documentation
```console
[tkloczko@barrel SPECS]$ rpmbuild -ba --with check --with failing_tests python-zmq.spec
warning: Downloading https://github.com/zeromq/pyzmq//archive/v22.2.1/python-zmq-22.2.1.tar.gz to /home/tkloczko/rpmbuild/SOURCES/python-zmq-22.2.1.tar.gz
warning: Downloading https://github.com/zeromq/pyzmq//pull/1619.patch#/python-zmq-Small-update-clarification-to-auth-docs.patch to /home/tkloczko/rpmbuild/SOURCES/python-zmq-Small-update-clarification-to-auth-docs.patch
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.a3TFSQ
+ umask 022
+ cd /home/tkloczko/rpmbuild/BUILD
+ cd /home/tkloczko/rpmbuild/BUILD
+ rm -rf pyzmq-22.2.1
+ /usr/bin/gzip -dc /home/tkloczko/rpmbuild/SOURCES/python-zmq-22.2.1.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd pyzmq-22.2.1
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/python-zmq-shebangs.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch -f
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/python-zmq-man3_level.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch -f
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/python-zmq-Small-update-clarification-to-auth-docs.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch -f
+ /usr/bin/rm -rf bundled
+ /usr/bin/chmod -x examples/pubsub/topics_pub.py examples/pubsub/topics_sub.py

[..]

running egg_info
creating pyzmq.egg-info
writing pyzmq.egg-info/PKG-INFO
writing dependency_links to pyzmq.egg-info/dependency_links.txt
writing requirements to pyzmq.egg-info/requires.txt
writing top-level names to pyzmq.egg-info/top_level.txt
writing manifest file 'pyzmq.egg-info/SOURCES.txt'
listing git files failed - pretending there aren't any
reading manifest file 'pyzmq.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'setupegg.py'
warning: no files found matching 'tox.ini'
warning: no files found matching '.travis.yml'
no previously-included directories found matching 'docs/build'
no previously-included directories found matching 'docs/gh-pages'
warning: no files found matching 'bundled/zeromq/COPYING'
warning: no directories found matching 'bundled/zeromq/include'
warning: no directories found matching 'bundled/zeromq/src'
warning: no directories found matching 'bundled/zeromq/tweetnacl'
warning: no directories found matching 'bundled/zeromq/external/wepoll'
warning: no previously-included files found matching 'bundled/zeromq/src/Makefile*'
warning: no previously-included files found matching 'bundled/zeromq/src/platform.hpp'
warning: no previously-included files found matching 'setup.cfg'
warning: no previously-included files found matching 'zmq/libzmq*'
warning: no previously-included files matching '.deps/*' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
warning: no previously-included files matching '.mailmap' found anywhere in distribution
warning: no previously-included files matching 'Makefile.am' found anywhere in distribution
warning: no previously-included files matching 'Makefile.in' found anywhere in distribution
adding license file 'COPYING.BSD'
adding license file 'COPYING.LESSER'
adding license file 'AUTHORS.md'
writing manifest file 'pyzmq.egg-info/SOURCES.txt'
+ PBR_VERSION=22.2.1
+ SETUPTOOLS_SCM_PRETEND_VERSION=22.2.1
+ SPHINXOPTS=-j48
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.2.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 328, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/pyzmq-22.2.1/docs/source/conf.py", line 65, in <module>
    import zmq
  File "/home/tkloczko/rpmbuild/BUILD/pyzmq-22.2.1/zmq/__init__.py", line 103, in <module>
    from zmq import backend
  File "/home/tkloczko/rpmbuild/BUILD/pyzmq-22.2.1/zmq/backend/__init__.py", line 32, in <module>
    raise original_error from None
  File "/home/tkloczko/rpmbuild/BUILD/pyzmq-22.2.1/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/tkloczko/rpmbuild/BUILD/pyzmq-22.2.1/zmq/backend/select.py", line 32, in select_backend
    mod = import_module(name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tkloczko/rpmbuild/BUILD/pyzmq-22.2.1/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (
ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (/home/tkloczko/rpmbuild/BUILD/pyzmq-22.2.1/zmq/backend/cython/__init__.py)
```

**Comment by minrk** [comment]
The docs assume an in-place build of pyzmq (`python3 setup.py build_ext --inplace`) by adding the repo root to sys.path.

If you're not doing that, you could patch [that][] out, or make it opt-out with an env variable or some such.

[that]: https://github.com/zeromq/pyzmq/blob/25bdeb54e4bd95d16e0c57080098af3da4b1116e/docs/source/conf.py#L21

**Comment by kloczek** [comment]
> 

> The docs assume an in-place build of pyzmq (`python3 setup.py build_ext --inplace`) by adding the repo root to sys.path.
> 
> If you're not doing that, you could patch [that](https://github.com/zeromq/pyzmq/blob/25bdeb54e4bd95d16e0c57080098af3da4b1116e/docs/source/conf.py#L21) out, or make it opt-out with an env variable or some such.

Using `python3 setup.py build_ext` is ALREADY deprecated from more than 3 years.
Please update your build procedures.
Currently used build procedure is described in PEP517.

**Comment by minrk** [comment]
To be clear, all build procedures are fully PEP517 and have been for years. I should have typed `pip install -e .`, which is the same. But anyway, this issue is closed because none of that is relevant anymore.

**Comment by kloczek** [comment]
> o be clear, all build procedures are fully PEP517 and have been for years. I should have typed `pip install -e .`, which is the same. But anyway, this issue is closed because none of that is relevant anymore.

So I completely do not understand why you recommend me to use deprecated procedure.

**Comment by minrk** [comment]
I'm not doing that. You are responding to a comment from years ago that is no longer accurate. It worked then, it doesn't now.
