### ISSUE TITLE
Getting ZMQError: Socket operation on non-socket when using asyncio and monitoring socket events

### ISSUE THREAD

**Issue by Jeducious** [zeromq/pyzmq#1623]
# Problem

I have a broker that binds a ROUTER socket. I've also tried replacing this with a SUB socket when this didn't work out. 

I try to connect a DEALER (and have tried PUB also) socket to the broker's ROUTER socket. Its important to me to know when a connection is successful, so I use a monitor socket to listen for the CONNECTED event. It seems to be that the use of the monitor socket is the problem as when polling, I get the error in the title. 

# Code

The config of this code uses PUB->SUB, but I have tested DEALER->ROUTER (where A->B means B binds, A connects).
Both fail with the same error.

### router_monitor_test.py
```Python
import ipaddress,time, asyncio, uuid

import zmq
import zmq.asyncio
from zmq.utils import monitor
parse_mon_msg = monitor.parse_monitor_message

z_cont = zmq.asyncio.Context.instance()

EVENT_NAME = 0
EVENT_DESCRIPTION = 1
ZMQ_EVENTS = { 
        "EVENT_ACCEPTED": (
        "CONNECTION ACCEPTED",
        """The zmq_socket has accepted a connection from a 
        remote peer. The event value is the FD of the underlying network zmq_socket.
        Warning: there is no guarantee that the FD is still valid 
        by the time your code receives this event."""
    ),
        "EVENT_ACCEPT_FAILED": (
        "CONNECTION NOT ACCEPTED", 
        """The zmq_socket has rejected a connection 
        from a remote peer. The event value is the errno generated by the accept
        call."""
    ),
    "EVENT_BIND_FAILED": (
        "BIND FAILED", 
        """The zmq_socket could not bind to a given interface. 
        The event value is the errno generated by the system bind call."""
    ),
    "EVENT_CONNECTED": (
        "CONNECTED", 
        """ The zmq_socket has successfully connected to a remote peer. 
        The event value is the file descriptor (FD) of the underlying network
        zmq_socket. Warning: there is no guarantee that the FD is still valid by 
        the time your code receives this event. """
    ),
    "EVENT_CONNECT_DELAYED": (
        "CONNECT_DELAYED", 
        """ A connect request on the zmq_socket is pending.
        The event value is unspecified. """
    ),
    "EVENT_CONNECT_RETRIED": (
        "CONNECT RETRIED", 
        """ A connect request failed, and is now being
        retried. The event value is the reconnect interval in milliseconds.
        Note that the reconnect interval is recalculated at each retry. 
        """
    ),
    "EVENT_CLOSED": (
        "CLOSED", 
        """The zmq_socket was closed. The event value is the FD of the 
        (now closed) network zmq_socket."""
    ),
    "EVENT_DISCONNECTED": (
        "DISCONNECTED", 
        """ The zmq_socket was disconnected unexpectedly. 
        The event value is the FD of the underlying network zmq_socket. 
        Warning: this zmq_socket will be closed."""
    ),
    "EVENT_HANDSHAKE_FAILED_AUTH": (
        "HANDSHAKE FAILED AUTH", 
        """ The ZMTP security mechanism 
            handshake failed due to an authentication failure. 
            The event value is the status code returned by the ZAP
            handler (i.e. 300, 400 or 500). """
    ),
    "EVENT_HANDSHAKE_FAILED_NO_DETAIL": (
        "HANDSHAKE FAILED NO DETAIL", 
        """ Unspecified error during handshake. 
        The event value is an errno. """
    ), 
    "EVENT_HANDSHAKE_FAILED_PROTOCOL": (
        "HANDSHAKE FAILED PROTOCOL", 
        """The ZMTP security mechanism handshake failed due to 
        some mechanism protocol error, either between the ZMTP 
        mechanism peers, or between the mechanism server and 
        the ZAP handler. This indicates a configuration or 
        implementation error in either peer resp. the ZAP handler. 
        The event value is one of the ZMQ_PROTOCOL_ERROR_* values"""
    ),
    "EVENT_HANDSHAKE_SUCCEEDED":(
        "HANDSHAKE SUCCEEDED", 
        """ The ZMTP security mechanism handshake succeeded. 
        The event value is unspecified """
    ),
    "EVENT_LISTENING":(
        "LISTENING", 
        """The zmq_socket was successfully bound to a network interface.
         The event value is the FD of the underlying network zmq_socket. 
         Warning: there is no guarantee that the FD is still valid by 
         the time your code receives this event."""
    )
}

ZMQ_EVENTS = {getattr(zmq.constants, event_name):description for event_name, description in ZMQ_EVENTS.items()\
    if hasattr(zmq.constants, event_name)}


class ConnectError(Exception):
    def __init__(self, message):
        # Call the base class constructor with the parameters it needs
        super().__init__(message)

class ConnectBase:
    """ base class - help est connections to components of the CRESS system """
    PEER_TYPE = "?"
    TYPE = "BASE"
    def __init__(
        self, 
        z_context=zmq.asyncio.Context.instance(), 
        peer_ip='0.0.0.0', 
        peer_port=-1,
        time_out=-1,
        logger = None
    ):
        """ Create a Context obj for connecting to a CR broker/CIP
        
        Arguments: 
            z_cont     -    zmq.asyncio.Context object
            peer_ip    -    string - override for ip address of broker/CIP
            peer_port  -    int - override for port # of broker/CIP
            time_out   -    float - time limit for a connection success event
            
        
        Description:
        
        A context object for managing connection from the host application
        (client side) to the CR broker/CIP process.
        
        """
        
        self.z_cont = z_context 
        
        if ipaddress.ip_address(peer_ip).is_unspecified:#use default in this 
                                                        #context
            self.peer_ip = self.PEER_ADDR
            
        else:
            
            self.peer_ip = peer_ip
            
        if peer_port < 0:
            
            self.peer_port = self.PEER_PORT#default
            
        else:
            
            self.peer_port = peer_port
            
        if time_out < 0:
            
            self.time_out = self.TIMEOUT
        
        else:
            
            self.time_out = time_out
        
        self.peer_endpoint = "".join([
            self.peer_ip,
            ":",
            str(self.peer_port)
        ])
        
    def times_up(self):
        
        return time.perf_counter() - self.start > self.time_out
        
        
    async def connect(self, sock=None):
        
        
        self.start = time.perf_counter()
        self.zmq_socket = sock or self.z_cont.socket(self.SOCK_TYPE)
        self.context_id = uuid.uuid4()
        self.inproc_addr = f"inproc://monitor_sock_{self.context_id}"
        #monitor for connect
        mon_sock = self.zmq_socket.get_monitor_socket(
            addr= self.inproc_addr
        )
        
        print(
             f"CRESS:{self.TYPE}: {self.context_id} "+\
             f"Connecting to {self.PEER_TYPE} at {self.peer_endpoint}"
         )
        #construct zmq_socket
        poller = zmq.asyncio.Poller()
        poller.register(mon_sock, zmq.POLLIN)
        
        await asyncio.sleep(2)
        
        self.zmq_socket.connect(f"tcp://{self.peer_endpoint}")
        
        while True:
            
            socks = dict(await poller.poll())
            
            if mon_sock in socks:
                
                event_ob = parse_mon_msg(mon_sock.recv_multipart().result())
                event = event_ob['event']
                value = str(event_ob['value'])
                endpoint = event_ob['endpoint'].decode('utf-8')
                
                print(
                    "".join([
                        f"CRESS:{self.TYPE}:EVENT: {self.context_id} ",
                        ZMQ_EVENTS[event][EVENT_NAME],
                        ":", 
                        value,
                        ":", 
                        endpoint]
                    )
                )
                
                if event == zmq.EVENT_CONNECTED:
                    print(
                        f"CRESS:{self.TYPE}: {self.context_id} Connected to {self.PEER_TYPE}"
                    )
                    sock = self.zmq_socket
                    break
                        
            if self.times_up():
                print(f"CRESS:{self.TYPE}: {self.context_id} : Couldn't Connect")
                
                raise ConnectError(
                    f"Couldn't connect to {self.PEER_TYPE} zmq_socket"
                )
                
            mon_sock.close(linger =0)
        
        return sock
    
class SessionSubConnect(ConnectBase):
    
    SOCK_TYPE = zmq.SUB
    PEER_TYPE = "Server Interface pub socket"
    TYPE = "Sessino zmq.SUB socket"
    PEER_PORT = 9998
    
class FileTransferRoutConnect(ConnectBase):
    
    SOCK_TYPE = zmq.ROUTER
    PEER_TYPE = "Server Session router socket"
    PEER_PORT = 9999
    TYPE = "Session zmq.ROUTER socket"
    
class FileTransferDealerConnect(ConnectBase):
    
    SOCK_TYPE = zmq.DEALER
    PEER_TYPE = "zmq.ROUTER Socket"
    PEER_PORT = 9998
    TYPE = "zmq.DEALER socket"


async def main():
    
    try:
        #create a listening socket
        sock = z_cont.socket(zmq.PUB)
        sock.bind('tcp://127.0.0.1:9998')
        
        sub = z_cont.socket(zmq.SUB)
        sub.setsockopt(zmq.SUBSCRIBE, b'')
        #create a connection helper obj
    #    connect_helper = FileTransferRoutConnect(
    #        z_context=z_cont, 
    #        peer_ip='127.0.0.1', 
    #        peer_port=-9998,
    #        time_out=10,
    #    )
        
        connect_helper = SessionSubConnect(
            z_context=z_cont, 
            peer_ip='127.0.0.1', 
            peer_port=-9998,
            time_out=10,
        )
    
        await connect_helper.connect(sock = sub)
        
    finally:
        
        sock.close(linger=0)

asyncio.run(main())

print("DONE")
```

# The output of the code

```Python
CRESS:Sessino zmq.SUB socket: 99563fbe-9529-4301-8ea0-b79722705f99 Connecting to Server Interface pub socket at 127.0.0.1:9998
CRESS:Sessino zmq.SUB socket:EVENT: 99563fbe-9529-4301-8ea0-b79722705f99 CONNECT_DELAYED:36:tcp://127.0.0.1:9998
Traceback (most recent call last):
  File "/Users/jamescrowther/Desktop/Crowdrender/Impatient_dev/router_monitor_test.py", line 286, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/jamescrowther/Desktop/Crowdrender/Impatient_dev/router_monitor_test.py", line 280, in main
    await connect_helper.connect(sock = sub)
  File "/Users/jamescrowther/Desktop/Crowdrender/Impatient_dev/router_monitor_test.py", line 196, in connect
    socks = dict(await poller.poll())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zmq/_future.py", line 63, in poll
    socket._add_recv_event('poll', future=watcher)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zmq/_future.py", line 353, in _add_recv_event
    timeout_ms = self._shadow_sock.rcvtimeo
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zmq/sugar/attrsettr.py", line 51, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zmq/sugar/attrsettr.py", line 63, in _get_attr_opt
    return self.get(opt)
  File "zmq/backend/cython/socket.pyx", line 488, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 262, in zmq.backend.cython.socket._getsockopt
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Socket operation on non-socket
```

# How to reproduce

I run the following from a terminal

```
>>>python3 router_monitor_test.py
```

# Machine and environment specs

## Python and zmq versions

pyzmq v22.1.0 on python 3.9.2, machine was a macintosh system.

## Hardware and OS

Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  Boot ROM Version:	427.140.8.0.0
  SMC Version (system):	2.28f7

OS : MacOS Catalina 10.15.7

# Does this code work anywhere else?
Yes! I have successfully the same ConnectBase.connect method inside an IsolatedAsyncioTestCase. I have a whole suite of tests that use the ConnectBase.connect method successfully in python 3.9.2. 

I've run these tests in the following contexts without a problem;

- VSCode running on the same hardware as above, which uses the same version of python as well. All tests using the ConnectBase.connect method work fine
- Inside GitHub actions setup on our repositories, tests are run from the command line using python (see below for the action yaml file)
- On windows, again via VSCode.

So it seems that using the ConnectBase.connect method works fine when run as part of an IsolatedAsyncioTestCase.

## GitHub actions yaml file

```Yaml
name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #- name: Lint with flake8
    #  run: |
    #    # stop the build if there are Python syntax errors or undefined names
    #   flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #   # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #   flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with python unittest
      run: |
        python3 -m unittest discover cress
        echo "Python Tests Exited with '$?'"
```

# My Request
Help!!! I am hoping that this is a simple error on my part. Having successfully built a whole suite of tests and debugged this, I am a bit confused why this code doesn't work outside of the test case environment. I've looked into python's implementation of the IsolatedAsyncioTestCase, and it doesn't seem like its doing something drastically different to what I am doing. 

I am also doubtful that the monitor socket implementation doesn't work for asyncio, it clearly does when used with the IsolatedAsyncioTestCase. So it seems like there may be either an edge case for pyzmq here, or I've made a blunder in how to use it properly. There isn't much in the way of examples of how to get this right in the pyzmq docs so if this is my error, I think it might help to at the least provide a text book e.g. of how to avoid what I've done wrong?

**Comment by Jeducious** [comment]
# Humble Pie being eaten right now

Wow, I think I am going senile. 

Ok, so, I did mention in the issue description above that I suspected a blunder on my part as a likely cause. With a bit more bashing my skull against the keyboard, eventually the reason came to light. Here's what I learned.

1. 99.99999% of the time, errors in code are my fault, I keep learning this lesson over and over.
2. Asking for help and publicising code seems to help make the error more obvious to myself
3. Indentation in python makes for interesting bugs
4. I think I need to sleep more.

# What the error actually was

Starting with what its not. Its 100% not an issue with pyzmq. The above code had an error of my making.

```Python

while True:

      try:

            socks = dict(await poller.poll())
            
            if mon_sock in socks:
                
                event_ob = parse_mon_msg(mon_sock.recv_multipart().result())
           #### Lines removed for clarity ####
                
           mon_sock.close(linger =0) ## BIG OOPS HERE -_-
           
```

What's clear from the above excerpt from my code, is that the mon_sock is being closed each time through the loop. That line was supposed to be run after the while loop ended. 

# Lesson Learned
For one, indentation requires attention to detail, this particular error was syntactically correct, but not what I intended, so it ran, but did something different to what I wanted. 

For another, maybe I pulled the emergency handle a little early posting this issue. Though it seemed that after I posted, I had fresh motivation and energy to go find the problem. I guess its less embarrassing to find such a simple error myself than having it pointed out to me 🤣
