### ISSUE TITLE
types are broken with py3.11.0a6

### ISSUE THREAD

**Issue by tacaswell** [zeromq/pyzmq#1676]
I am seeing import errors that look like:

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.11/site-packages/zmq/__init__.py", line 108, in <module>
    from zmq import sugar
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.11/site-packages/zmq/sugar/__init__.py", line 8, in <module>
    from zmq.sugar import context, frame, poll, socket, tracker, version
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.11/site-packages/zmq/sugar/context.py", line 35, in <module>
    class Context(ContextBase, AttributeSetter, Generic[ST]):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tcaswell/.pybuild/bleeding/lib/python3.11/typing.py", line 1731, in __init_subclass__
    raise TypeError(f"Some type variables ({s_vars}) are"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Some type variables (~T) are not listed in Generic[+ST]

```

which bisects back to 2dc67d544c8fc853c9acca3cef7f89803d92298a

I do not see this issue with py310 and have only begun to see these failures locally recently which makes me think this is actually a CPython change that broke it. However I have not bisected this back in CPython to sort what changed there.

**Comment by minrk** [comment]
Thanks for testing! I think #1677 may fix it
