### ISSUE TITLE
BUG: You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.

### ISSUE THREAD

**Issue by xiezhipeng-git** [zeromq/pyzmq#1855]
### What pyzmq version?

Version: 25.0.2

### What libzmq version?

I don't know And not found: zmq not found: libzmq

### Python version (and how it was installed)

3.10.6

### OS

22.04 wsl

### What happened?

[A bug happened!](https://github.com/microsoft/vscode-jupyter/issues/8630)

### Code to reproduce bug

```python
[A bug happened!](https://github.com/microsoft/vscode-jupyter/issues/8630)
```

### Traceback, if applicable

```shell
StdErr from Kernel Process /home/xzpwsl2/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(

warn 00:31:36.606: StdErr from Kernel Process /home/xzpwsl2/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2499: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '00cb405d-8213-443f-9b68-d0478c62b5bc' instead of 'b"00cb405d-8213-443f-9b68-d0478c62b5bc"'.
  warn(

info 00:31:36.820: Got new session fc26fe45-9a26-48b2-a946-fded0348d751
info 00:31:36.820: Started new restart session
error 00:32:37.694: Disposing session as kernel process died ExitCode: undefined, Reason: /home/xzpwsl2/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/home/xzpwsl2/.local/lib/python3.10/site-packages/traitlets/traitlets.py:2499: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '00cb405d-8213-443f-9b68-d0478c62b5bc' instead of 'b"00cb405d-8213-443f-9b68-d0478c62b5bc"'.
  warn(

info 00:32:37.698: Dispose Kernel process 1585.
error 00:32:37.699: Raw kernel process exited code: undefined
error 00:32:37.722: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (/home/xzpwsl2/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:32419)
	at /home/xzpwsl2/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:51471
	at Map.forEach (<anonymous>)
	at y._clearKernelState (/home/xzpwsl2/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:51456)
	at y.dispose (/home/xzpwsl2/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:44938)
	at /home/xzpwsl2/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:96826
	at ee (/home/xzpwsl2/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1589492)
	at jh.dispose (/home/xzpwsl2/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:96802)
	at Lh.dispose (/home/xzpwsl2/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:104079)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
```

### More info

vscode jupyter wsl windows11 python3.10.6

**Comment by minrk** [comment]
This traceback doesn't show any errors or messages related to pyzmq. hmac, etc. is in jupyter-client, not related to pyzmq.
