### ISSUE TITLE
BUG: zmq.ROUTER_NOTIFY

### ISSUE THREAD

**Issue by adhish9899** [zeromq/pyzmq#1974]
### This is a pyzmq bug

- [ ] This is a pyzmq-specific bug, not an issue of zmq socket behavior. Don't worry if you're not sure! We'll figure it out together.

### What pyzmq version?

26.0.0b2

### What libzmq version?

4.3.5

### Python version (and how it was installed)

Python 3.11 installed via conda-forge

### OS

ubuntu 22.04

### What happened?

A bug happened! 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_zmq.py", line 780, in zmq.backend.cython._zmq.Socket.set
  File "_zmq.py", line 1367, in zmq.backend.cython._zmq._setsockopt
  File "_zmq.py", line 164, in zmq.backend.cython._zmq._check_rc
zmq.error.ZMQError: Invalid argument

### Code to reproduce bug

```python
import zmq

context = zmq.Context()
socket = context.socket(zmq.ROUTER) 
socket.setsockopt(zmq.ROUTER_NOTIFY, zmq.NOTIFY_CONNECT)
```

### Traceback, if applicable

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_zmq.py", line 780, in zmq.backend.cython._zmq.Socket.set
  File "_zmq.py", line 1367, in zmq.backend.cython._zmq._setsockopt
  File "_zmq.py", line 164, in zmq.backend.cython._zmq._check_rc
zmq.error.ZMQError: Invalid argument
```

**Comment by minrk** [comment]
This is the same as #1973, so I am closing it as a duplicate. ROUTER_NOTIFY is a draft feature in libzmq, so you must use libzmq with drafts enabled.
