### ISSUE TITLE
Install procedure doesn't work with pypy but does with cpython

### ISSUE THREAD

**Issue by easytiger** [zeromq/pyzmq#377]
When i follow the install procedure with pypy the install fails. The same procedure works for cpython.

```
$ pypy-c setup.py configure --zmq=../zeromq_3.2.3_install/ --inplace
running configure
cc -O2 -fPIC -Wimplicit -I../zeromq_3.2.3_install/include -c build/temp.linux-x86_64-2.7/scratch/check_sys_un.c -o build/temp.linux-x86_64-2.7/scratch/check_sys_un.o
cc build/temp.linux-x86_64-2.7/scratch/check_sys_un.o -L../zeromq_3.2.3_install/lib -Wl,-R/home/foo/zeromq_3.2.3_install/lib -lzmq -o build/temp.linux-x86_64-2.7/scratch/check_sys_un
PyPy: Nothing to configure
```

Note when run in cpython this configures and builds lots of things

```
$ pypy-c setup.py install  --prefix=`pwd`/pyzmq-13.0.2-inst
<.. long list of installed py/pyc files..>
Writing /home/foo/pyzmq-13.0.2/pyzmq-13.0.2-inst/site-packages/pyzmq-13.0.2-py2.7.egg-info


$ cd pyzmq-13.0.2-inst
$ pypy-c -c "import zmq"
site-packages/zmq/cffi_core/__pycache__/_cffi__g5368a726x67d4e236.c:25:17: error: zmq.h: No such file or directory
site-packages/zmq/cffi_core/__pycache__/_cffi__g5368a726x67d4e236.c: In _cffi_f_zmq_:
site-packages/zmq/cffi_core/__pycache__/_cffi__g5368a726x67d4e236.c:28: warning: implicit declaration of zmq_
Traceback (most recent call last):
  File "app_main.py", line 72, in run_toplevel
  File "app_main.py", line 562, in run_it
  File "<string>", line 1, in <module>
  File "/home/foo/lib/pyzmq-13.0.2/pyzmq-13.0.2-inst/site-packages/zmq/__init__.py", line 52, in <module>
    from zmq.sugar import backend
  File "/home/foo/lib/pyzmq-13.0.2/pyzmq-13.0.2-inst/site-packages/zmq/sugar/__init__.py", line 16, in <module>
    from zmq.sugar import (
  File "/home/foo/lib/pyzmq-13.0.2/pyzmq-13.0.2-inst/site-packages/zmq/sugar/constants.py", line 16, in <module>
    from .backend import constants
  File "/home/foo/lib/pyzmq-13.0.2/pyzmq-13.0.2-inst/site-packages/zmq/sugar/backend.py", line 29, in <module>
    from zmq.cffi_core import (
  File "/home/foo/lib/pyzmq-13.0.2/pyzmq-13.0.2-inst/site-packages/zmq/cffi_core/__init__.py", line 12, in <module>
    from zmq.cffi_core import (constants, error, message, context, socket,
  File "/home/foo/lib/pyzmq-13.0.2/pyzmq-13.0.2-inst/site-packages/zmq/cffi_core/constants.py", line 4, in <module>
    from ._cffi import C, constant_names, zmq_version_info
  File "/home/foo/lib/pyzmq-13.0.2/pyzmq-13.0.2-inst/site-packages/zmq/cffi_core/_cffi.py", line 195, in <module>
    "Please check that you have zeromq headers and libraries." % e)
ImportError: PyZMQ CFFI backend couldn't find zeromq: CompileError: command 'cc' failed with exit status 1
Please check that you have zeromq headers and libraries.
versionfunction versionfunction
```

Versions:

```
$ pypy-c --version
Python 2.7.3 (3b53c1137d001c9292c47006c1418e8b895c8941, May 21 2013, 15:12:30)
[PyPy 2.0.1 with GCC 4.1.2 20080704 (Red Hat 4.1.2-48)]

$ python --version
Python 2.7.2
```

**Comment by rpcoelho17** [comment]
I tried typing the command above in the terminal prompt (OSX-mac) and I am still getting the error about zeromq.  here are the last few lines:

    mod = __import__(name, fromlist=public_api)
  File "/Users/rodrigocoelho/pypy2/site-packages/zmq/backend/cffi/__init__.py", line 6, in <module>
    from zmq.backend.cffi import (constants, error, message, context, socket,
  File "/Users/rodrigocoelho/pypy2/site-packages/zmq/backend/cffi/constants.py", line 4, in <module>
    from ._cffi import C, c_constant_names
  File "/Users/rodrigocoelho/pypy2/site-packages/zmq/backend/cffi/_cffi.py", line 100, in <module>
    "Please check that you have zeromq headers and libraries." % e)
ImportError: PyZMQ CFFI backend couldn't find zeromq: Cannot load library /Users/rodrigocoelho/pypy2/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.pypy-41.so: dlopen(/Users/rodrigocoelho/pypy2/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.pypy-41.so, 2): Symbol not found: _zmq_bind
  Referenced from: /Users/rodrigocoelho/pypy2/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.pypy-41.so
  Expected in: flat namespace
 in /Users/rodrigocoelho/pypy2/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.pypy-41.so
Please check that you have zeromq headers and libraries.

I'm a mechanical engineer so if I have to compile or add a path somewhere would it be possible to be a little more detailed on the commands I would have to issue and in which directories?

Thanks in advance for your help,
Rod.
