### ISSUE TITLE
LINGER broken on Python 3.4.0?

### ISSUE THREAD

**Issue by CleanCut** [zeromq/pyzmq#537]
Using python 3.4.0 on OS X 10.9.2 (Mavericks) OR on CentOS 6.5 (fully patched), I can't get ZMQ to _not_ hang on exit.  So either something is broken, or someone needs to clue me in to what I'm doing wrong.

Here's my versions on OS X:

```
Python 3.4.0 (default, Mar 27 2014, 11:16:52)
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.38)] on darwin
>>> zmq.zmq_version()
'4.0.4'
>>> zmq.pyzmq_version()
'14.1.1'
```

Here's my versions on CentOS 6.5:

```
Python 3.4.0 (default, Apr  8 2014, 14:10:50)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
>>> zmq.zmq_version()
'4.0.4'
>>> zmq.pyzmq_version()
'14.1.1'
```

Here are my examples of hanging (never exiting the python process).  The behavior is identical on both of my OS's, so I'll just post each example once.  I initially discovered this behavior in the small file I was making, but these interactive examples duplicate the behavior.

REQ socket, linger on socket before connect:

```
>>> import zmq
>>> c = zmq.Context()
>>> s = c.socket(zmq.REQ)
>>> s.setsockopt(zmq.LINGER, 0)
>>> s.connect('tcp://localhost:3333')
>>> s.send(b'')
>>> ^D
(hangs forever)
```

Doing the linger after the connect doesn't make a difference:

```
>>> import zmq
>>> c = zmq.Context()
>>> s = c.socket(zmq.REQ)
>>> s.connect('tcp://localhost:3333')
>>> s.setsockopt(zmq.LINGER, 0)
>>> s.send(b'')
>>> ^D
(hangs forever)
```

Doing bind instead of connect doesn't make a difference:

```
>>> import zmq
>>> c = zmq.Context()
>>> s = c.socket(zmq.REQ)
>>> s.setsockopt(zmq.LINGER, 0)
>>> s.bind('tcp://0.0.0.0:3333')
>>> s.send(b'')
>>> ^D
(hangs forever)
```

Doing the linger on the context doesn't make a difference:

```
>>> import zmq
>>> c = zmq.Context()
>>> c.setsockopt(zmq.LINGER, 0)
>>> s = c.socket(zmq.REQ)
>>> s.connect('tcp://localhost:3333')
>>> s.send(b'')
>>> ^D
(hangs forever)
```

Changing the socket type doesn't make a difference:

```
>>> import zmq
>>> c = zmq.Context()
>>> s = c.socket(zmq.PUB)
>>> s.setsockopt(zmq.LINGER, 0)
>>> s.connect('tcp://localhost:3333')
>>> s.send(b'')
>>> ^D
(hangs forever)
```

And lastly, changing the URL method doesn't make a difference:

```
>>> import zmq
>>> c = zmq.Context()
>>> s = c.socket(zmq.REQ)
>>> s.setsockopt(zmq.LINGER, 0)
>>> s.connect('ipc:///tmp/somefile')
>>> s.send(b'')
>>> ^D
(hangs forever)
```

**Help!**

**Comment by enkore** [comment]
FTR I've seen this bug with pyzmq 16.0.0 on Python 3.5.2. Or at least I think this is the bug. GDB trace from a hung process:

```
  Thread 1 (Thread 0x7f79293d2400 (LWP 5620)):
  #0  0x00007f792885c48d in poll () from /usr/lib/libc.so.6
  #1  0x00007f792020050a in zmq::signaler_t::wait (this=this@entry=0x1999e68, timeout_=timeout_@entry=-1) at src/signaler.cpp:218
  #2  0x00007f79201ec240 in zmq::mailbox_t::recv (this=this@entry=0x1999e08, cmd_=cmd_@entry=0x7ffd1666dc30, timeout_=timeout_@entry=-1) at src/mailbox.cpp:80
> #3  0x00007f79201dd8bc in zmq::ctx_t::terminate (this=0x1999d70) at src/ctx.cpp:165
> #4  0x00007f791f400c38 in __pyx_f_3zmq_7backend_6cython_7context_7Context__term (__pyx_v_self=0x7f7921698358) at zmq/backend/cython/context.c:1954
  #5  __pyx_pf_3zmq_7backend_6cython_7context_7Context_6term (__pyx_v_self=0x7f7921698358) at zmq/backend/cython/context.c:2066
  #6  __pyx_pw_3zmq_7backend_6cython_7context_7Context_7term (__pyx_v_self=0x7f7921698358, unused=<optimized out>) at zmq/backend/cython/context.c:2032
  #7  0x00007f7928e5f1bc in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
  #8  0x00007f7928e602c3 in ?? () from /usr/lib/libpython3.5m.so.1.0
  #9  0x00007f7928e603a3 in PyEval_EvalCodeEx () from /usr/lib/libpython3.5m.so.1.0
  #10 0x00007f7928dcb008 in ?? () from /usr/lib/libpython3.5m.so.1.0
  #11 0x00007f7928da02d7 in PyObject_Call () from /usr/lib/libpython3.5m.so.1.0
  #12 0x00007f7928db6d44 in ?? () from /usr/lib/libpython3.5m.so.1.0
  #13 0x00007f7928da02d7 in PyObject_Call () from /usr/lib/libpython3.5m.so.1.0
  #14 0x00007f7928e56a87 in PyEval_CallObjectWithKeywords () from /usr/lib/libpython3.5m.so.1.0
  #15 0x00007f7928dfd31d in ?? () from /usr/lib/libpython3.5m.so.1.0
  #16 0x00007f7928e9923f in ?? () from /usr/lib/libpython3.5m.so.1.0
> #17 0x00007f7928e9a071 in _PyGC_CollectNoFail () from /usr/lib/libpython3.5m.so.1.0
> #18 0x00007f7928e723c8 in PyImport_Cleanup () from /usr/lib/libpython3.5m.so.1.0
> #19 0x00007f7928e7cbb4 in Py_Finalize () from /usr/lib/libpython3.5m.so.1.0
  #20 0x00007f7928e7d868 in Py_Exit () from /usr/lib/libpython3.5m.so.1.0
  #21 0x00007f7928e805a8 in ?? () from /usr/lib/libpython3.5m.so.1.0
  #22 0x00007f7928e8098d in PyErr_PrintEx () from /usr/lib/libpython3.5m.so.1.0
  #23 0x00007f7928e81da5 in PyRun_SimpleFileExFlags () from /usr/lib/libpython3.5m.so.1.0
  #24 0x00007f7928e9869c in Py_Main () from /usr/lib/libpython3.5m.so.1.0
  #25 0x0000000000400af0 in main ()
```

**Comment by minrk** [comment]
@enkore do you have an example script that reproduces it?
