### ISSUE TITLE
Cannot load on 64bit Windows XP due to "missing procedure"

### ISSUE THREAD

**Issue by patricktokeeffe** [zeromq/pyzmq#579]
I use [WinPython](winpython.sourceforge.net/) and with the latest 64bit release, 2.7.6.4 (python 2.7.6 amd64), an unhandled `WindowsError` prevents applications like Spyder and IPython QtConsole from loading. The previous major version winpython-64bit-2.7.5.3 (python 2.7.5 amd64) does not have this issue.

I had [originally filed](https://github.com/ipython/ipython/issues/6348) this with IPython because it occurs during the IPython load sequence. More specifically, though, it occurs when IPython tries to import `zmq`. I do see that `ctypes` is entered prior to the error occuring so I don't expect this to be solved solely within zmq.

A screenshot of the QtConsole error is attached. The following console output was obtained by adding "pause" to the end of `/scripts/spyder.bat` and `/scripts/spyder_light.bat`:

````python
Traceback (most recent call last):
  File "spyder", line 3, in <module>
    start_app.main()
  File "C:\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\spyderlib\start_app.py", line 72, in main
    from spyderlib import spyder
  File "C:\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\spyderlib\spyder.py", line 118, in <module>
    from spyderlib.plugins.ipythonconsole import IPythonConsole
  File "C:\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\spyderlib\plugins\ipythonconsole.py", line 31, in <module>
    from IPython.lib.kernel import find_connection_file, get_connection_info
  File "C:\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\IPython\lib\kernel.py", line 11, in <module>
    from IPython.kernel.connect import *
  File "C:\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\IPython\kernel\__init__.py", line 4, in <module>
    from . import zmq
  File "C:\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\IPython\kernel\zmq\__init__.py", line 14, in <module>
    check_for_zmq('2.1.11', 'IPython.kernel.zmq')
  File "C:\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\IPython\utils\zmqrelated.py", line 35, in check_for_zmq
    import zmq
  File "C:\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\zmq\__init__.py", line 33, in <module>
    _libzmq = ctypes.cdll.LoadLibrary(bundled[0])
  File "C:\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 127] The specified procedure could not be found
````

![spyder error](https://cloud.githubusercontent.com/assets/1348834/4019432/2d34597c-2a6d-11e4-9b28-f448c610f2b1.png)

**Comment by cgohlke** [comment]
See https://github.com/zeromq/pyzmq/issues/521#issuecomment-39649154

**Comment by minrk** [comment]
@cgohlke thanks
