### ISSUE TITLE
AttributeError: 'module' object has no attribute 'has'

### ISSUE THREAD

**Issue by AndreLouisCaron** [zeromq/pyzmq#655]
I just checked out the latest PyZMQ master and installed it from source by running:

    python setup.py install --zmq=bundled

in a new virtual environment.  Then, when I `import zmq`, I get this error:

    >>> import zmq
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Users\ACaron\Desktop\develop\pyzmq\site\lib\site-packages\zmq\__init__.py", line 49, in <module>
        from zmq import backend
      File "C:\Users\ACaron\Desktop\develop\pyzmq\site\lib\site-packages\zmq\backend\__init__.py", line 41, in <module>
        reraise(*exc_info)
      File "C:\Users\ACaron\Desktop\develop\pyzmq\site\lib\site-packages\zmq\backend\__init__.py", line 29, in <module>
        _ns = select_backend(first)
      File "C:\Users\ACaron\Desktop\develop\pyzmq\site\lib\site-packages\zmq\backend\select.py", line 38, in select_backend
        ns[key] = getattr(mod, key)
    AttributeError: 'module' object has no attribute 'has'

Everything seems to have built fine.  Any idea what's going wrong?

**Comment by AndreLouisCaron** [comment]
I dug a bit and noticed that the generated `.c` file for `utils.pyx` did not contain the definition for the `has` function.   I reinstalled Python 2.7.9, virtualenv, cython, cleaned everything and the error disappeared...

**Comment by minrk** [comment]
I think I've seen this before when upgrading pyzmq while it's already in use, and it doesn't successfully overwrite all files (a Windows filesystem problem). Can you `pip uninstall pyzmq` then `pip install pyzmq`?

**Comment by AndreLouisCaron** [comment]
Since I already fixed it be reinstalling everything, it will be hard to confirm whether the uninstall fixes it.  If I run into it again, I'll try to use that instead of reinstalling everything.  Thanks!

**Comment by minrk** [comment]
Okay, thanks.
