### ISSUE TITLE
Value referenced before assignment in sugar/socket.py

### ISSUE THREAD

**Issue by dwf** [zeromq/pyzmq#667]
Looks like an untested exception pathway, maybe.

```
Traceback (most recent call last):
  File "/Users/dwf/miniconda/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Users/dwf/miniconda/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dwf/src/fuel/fuel/utils/zmq.py", line 418, in launch_ventilator
    self.ventilator_hwm, self.sink_port)
  File "/Users/dwf/src/fuel/fuel/utils/zmq.py", line 150, in setup_sockets
    self._sender.hwm = sender_hwm
  File "/Users/dwf/miniconda/lib/python3.4/site-packages/zmq/sugar/attrsettr.py", line 18, in __setattr__
    object.__setattr__(self, key, value)
  File "/Users/dwf/miniconda/lib/python3.4/site-packages/zmq/sugar/socket.py", line 226, in set_hwm
    raised = e
```

Package versions:
```
dwf@skyquake:~/src/fuel$ conda list |grep mq
pyzmq                     14.4.1                   py34_0
zeromq                    4.0.4                         0
```

**Comment by dwf** [comment]
Looks like [this line](https://github.com/zeromq/pyzmq/blob/master/zmq/sugar/socket.py#L265) is missing `as e`.
