### ISSUE TITLE
zmq.tests.test_cffi_backend.TestCFFIBackend tests incorrectly skipped and failing with Python 3

### ISSUE THREAD

**Issue by Arfrever** [zeromq/pyzmq#684]
`zmq.tests.test_cffi_backend.TestCFFIBackend` tests should not be skipped with CPython when CFFI is installed for CPython.
After unskipping of these tests, they pass with CPython 2.
After unskipping of these tests, some of them pass with CPython 3, but others cause errors with CPython 3 and most likely also with Python 3 version of PyPy.
I use ZeroMQ 4.1.1.

Result of test suite of PyZMQ git trunk with CPython 3.4 after unskipping of these tests:
```
$ PYTHONPATH="build/lib.linux-x86_64-3.4" nosetests-3.4 -s -v -w build/lib.linux-x86_64-3.4/zmq/tests
...
test_zmq_bind (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ERROR
test_zmq_bind_connect (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ERROR
test_zmq_ctx_new_destroy (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ok
test_zmq_getsockopt (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ERROR
test_zmq_msg_data (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ERROR
test_zmq_msg_init_close (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ok
test_zmq_msg_init_data (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ERROR
test_zmq_msg_init_size (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ok
test_zmq_poll (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ERROR
test_zmq_recv (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ERROR
test_zmq_send (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ERROR
test_zmq_setsockopt (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ERROR
test_zmq_sleep (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ok
test_zmq_socket_open_close (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ok
test_zmq_stopwatch_functions (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ok
test_zmq_version_info (zmq.tests.test_cffi_backend.TestCFFIBackend) ... ok
...
======================================================================
ERROR: test_zmq_bind (zmq.tests.test_cffi_backend.TestCFFIBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyzmq/build/lib.linux-x86_64-3.4/zmq/tests/test_cffi_backend.py", line 89, in test_zmq_bind
    assert 0 == C.zmq_bind(socket, 'tcp://*:4444')
TypeError: initializer for ctype 'char *' must be a bytes or list or tuple, not str

======================================================================
ERROR: test_zmq_bind_connect (zmq.tests.test_cffi_backend.TestCFFIBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyzmq/build/lib.linux-x86_64-3.4/zmq/tests/test_cffi_backend.py", line 101, in test_zmq_bind_connect
    assert 0 == C.zmq_bind(socket1, 'tcp://*:4444')
TypeError: initializer for ctype 'char *' must be a bytes or list or tuple, not str

======================================================================
ERROR: test_zmq_getsockopt (zmq.tests.test_cffi_backend.TestCFFIBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyzmq/build/lib.linux-x86_64-3.4/zmq/tests/test_cffi_backend.py", line 65, in test_zmq_getsockopt
    identity = ffi.new('char[]', 'zmq')
  File "/usr/lib64/python3.4/site-packages/cffi/api.py", line 237, in new
    return self._backend.newp(cdecl, init)
TypeError: initializer for ctype 'char[]' must be a bytes or list or tuple, not str

======================================================================
ERROR: test_zmq_msg_data (zmq.tests.test_cffi_backend.TestCFFIBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyzmq/build/lib.linux-x86_64-3.4/zmq/tests/test_cffi_backend.py", line 139, in test_zmq_msg_data
    message = ffi.new('char[]', 'Hello')
  File "/usr/lib64/python3.4/site-packages/cffi/api.py", line 237, in new
    return self._backend.newp(cdecl, init)
TypeError: initializer for ctype 'char[]' must be a bytes or list or tuple, not str

======================================================================
ERROR: test_zmq_msg_init_data (zmq.tests.test_cffi_backend.TestCFFIBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyzmq/build/lib.linux-x86_64-3.4/zmq/tests/test_cffi_backend.py", line 126, in test_zmq_msg_init_data
    message = ffi.new('char[5]', 'Hello')
  File "/usr/lib64/python3.4/site-packages/cffi/api.py", line 237, in new
    return self._backend.newp(cdecl, init)
TypeError: initializer for ctype 'char[5]' must be a bytes or list or tuple, not str

======================================================================
ERROR: test_zmq_poll (zmq.tests.test_cffi_backend.TestCFFIBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyzmq/build/lib.linux-x86_64-3.4/zmq/tests/test_cffi_backend.py", line 217, in test_zmq_poll
    r1 = C.zmq_bind(receiver, 'tcp://*:3333')
TypeError: initializer for ctype 'char *' must be a bytes or list or tuple, not str

======================================================================
ERROR: test_zmq_recv (zmq.tests.test_cffi_backend.TestCFFIBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyzmq/build/lib.linux-x86_64-3.4/zmq/tests/test_cffi_backend.py", line 185, in test_zmq_recv
    assert 0 == C.zmq_bind(receiver, 'tcp://*:2222')
TypeError: initializer for ctype 'char *' must be a bytes or list or tuple, not str

======================================================================
ERROR: test_zmq_send (zmq.tests.test_cffi_backend.TestCFFIBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyzmq/build/lib.linux-x86_64-3.4/zmq/tests/test_cffi_backend.py", line 159, in test_zmq_send
    assert 0 == C.zmq_bind(receiver, 'tcp://*:7777')
TypeError: initializer for ctype 'char *' must be a bytes or list or tuple, not str

======================================================================
ERROR: test_zmq_setsockopt (zmq.tests.test_cffi_backend.TestCFFIBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyzmq/build/lib.linux-x86_64-3.4/zmq/tests/test_cffi_backend.py", line 52, in test_zmq_setsockopt
    identity = ffi.new('char[3]', 'zmq')
  File "/usr/lib64/python3.4/site-packages/cffi/api.py", line 237, in new
    return self._backend.newp(cdecl, init)
TypeError: initializer for ctype 'char[3]' must be a bytes or list or tuple, not str

```

**Comment by Arfrever** [comment]
Fix:
```
--- zmq/tests/test_cffi_backend.py
+++ zmq/tests/test_cffi_backend.py
@@ -22,8 +22,8 @@
 class TestCFFIBackend(TestCase):
     
     def setUp(self):
-        if not have_ffi_backend or not 'PyPy' in sys.version:
-            raise SkipTest('PyPy Tests Only')
+        if not have_ffi_backend:
+            raise SkipTest('CFFI not available')
 
     def test_zmq_version_info(self):
         version = zmq_version_info()
@@ -49,7 +49,7 @@
         ctx = C.zmq_ctx_new()
         socket = C.zmq_socket(ctx, PUSH)
 
-        identity = ffi.new('char[3]', 'zmq')
+        identity = ffi.new('char[3]', b'zmq')
         ret = C.zmq_setsockopt(socket, IDENTITY, ffi.cast('void*', identity), 3)
 
         assert ret == 0
@@ -62,7 +62,7 @@
         ctx = C.zmq_ctx_new()
         socket = C.zmq_socket(ctx, PUSH)
 
-        identity = ffi.new('char[]', 'zmq')
+        identity = ffi.new('char[]', b'zmq')
         ret = C.zmq_setsockopt(socket, IDENTITY, ffi.cast('void*', identity), 3)
         assert ret == 0
 
@@ -74,9 +74,9 @@
                             option_len)
 
         assert ret == 0
-        assert ffi.string(ffi.cast('char*', option))[0] == "z"
-        assert ffi.string(ffi.cast('char*', option))[1] == "m"
-        assert ffi.string(ffi.cast('char*', option))[2] == "q"
+        assert ffi.string(ffi.cast('char*', option))[0:1] == b"z"
+        assert ffi.string(ffi.cast('char*', option))[1:2] == b"m"
+        assert ffi.string(ffi.cast('char*', option))[2:3] == b"q"
         assert ctx != ffi.NULL
         assert ffi.NULL != socket
         assert 0 == C.zmq_close(socket)
@@ -86,7 +86,7 @@
         ctx = C.zmq_ctx_new()
         socket = C.zmq_socket(ctx, 8)
 
-        assert 0 == C.zmq_bind(socket, 'tcp://*:4444')
+        assert 0 == C.zmq_bind(socket, b'tcp://*:4444')
         assert ctx != ffi.NULL
         assert ffi.NULL != socket
         assert 0 == C.zmq_close(socket)
@@ -98,8 +98,8 @@
         socket1 = C.zmq_socket(ctx, PUSH)
         socket2 = C.zmq_socket(ctx, PULL)
 
-        assert 0 == C.zmq_bind(socket1, 'tcp://*:4444')
-        assert 0 == C.zmq_connect(socket2, 'tcp://127.0.0.1:4444')
+        assert 0 == C.zmq_bind(socket1, b'tcp://*:4444')
+        assert 0 == C.zmq_connect(socket2, b'tcp://127.0.0.1:4444')
         assert ctx != ffi.NULL
         assert ffi.NULL != socket1
         assert ffi.NULL != socket2
@@ -123,7 +123,7 @@
 
     def test_zmq_msg_init_data(self):
         zmq_msg = ffi.new('zmq_msg_t*')
-        message = ffi.new('char[5]', 'Hello')
+        message = ffi.new('char[5]', b'Hello')
 
         assert 0 == C.zmq_msg_init_data(zmq_msg,
                                         ffi.cast('void*', message),
@@ -136,7 +136,7 @@
 
     def test_zmq_msg_data(self):
         zmq_msg = ffi.new('zmq_msg_t*')
-        message = ffi.new('char[]', 'Hello')
+        message = ffi.new('char[]', b'Hello')
         assert 0 == C.zmq_msg_init_data(zmq_msg,
                                         ffi.cast('void*', message),
                                         5,
@@ -146,7 +146,7 @@
         data = C.zmq_msg_data(zmq_msg)
 
         assert ffi.NULL != zmq_msg
-        assert ffi.string(ffi.cast("char*", data)) == 'Hello'
+        assert ffi.string(ffi.cast("char*", data)) == b'Hello'
         assert 0 == C.zmq_msg_close(zmq_msg)
 
 
@@ -156,13 +156,13 @@
         sender = C.zmq_socket(ctx, REQ)
         receiver = C.zmq_socket(ctx, REP)
 
-        assert 0 == C.zmq_bind(receiver, 'tcp://*:7777')
-        assert 0 == C.zmq_connect(sender, 'tcp://127.0.0.1:7777')
+        assert 0 == C.zmq_bind(receiver, b'tcp://*:7777')
+        assert 0 == C.zmq_connect(sender, b'tcp://127.0.0.1:7777')
 
         time.sleep(0.1)
 
         zmq_msg = ffi.new('zmq_msg_t*')
-        message = ffi.new('char[5]', 'Hello')
+        message = ffi.new('char[5]', b'Hello')
 
         C.zmq_msg_init_data(zmq_msg,
                             ffi.cast('void*', message),
@@ -182,13 +182,13 @@
         sender = C.zmq_socket(ctx, REQ)
         receiver = C.zmq_socket(ctx, REP)
 
-        assert 0 == C.zmq_bind(receiver, 'tcp://*:2222')
-        assert 0 == C.zmq_connect(sender, 'tcp://127.0.0.1:2222')
+        assert 0 == C.zmq_bind(receiver, b'tcp://*:2222')
+        assert 0 == C.zmq_connect(sender, b'tcp://127.0.0.1:2222')
 
         time.sleep(0.1)
 
         zmq_msg = ffi.new('zmq_msg_t*')
-        message = ffi.new('char[5]', 'Hello')
+        message = ffi.new('char[5]', b'Hello')
 
         C.zmq_msg_init_data(zmq_msg,
                             ffi.cast('void*', message),
@@ -214,11 +214,11 @@
         sender = C.zmq_socket(ctx, REQ)
         receiver = C.zmq_socket(ctx, REP)
 
-        r1 = C.zmq_bind(receiver, 'tcp://*:3333')
-        r2 = C.zmq_connect(sender, 'tcp://127.0.0.1:3333')
+        r1 = C.zmq_bind(receiver, b'tcp://*:3333')
+        r2 = C.zmq_connect(sender, b'tcp://127.0.0.1:3333')
 
         zmq_msg = ffi.new('zmq_msg_t*')
-        message = ffi.new('char[5]', 'Hello')
+        message = ffi.new('char[5]', b'Hello')
 
         C.zmq_msg_init_data(zmq_msg,
                             ffi.cast('void*', message),
@@ -270,7 +270,7 @@
         assert ret == 0
 
         zmq_msg_again = ffi.new('zmq_msg_t*')
-        message_again = ffi.new('char[11]', 'Hello Again')
+        message_again = ffi.new('char[11]', b'Hello Again')
 
         C.zmq_msg_init_data(zmq_msg_again,
                             ffi.cast('void*', message_again),
```

**Comment by minrk** [comment]
It is indeed intended to skip the CFFI backend on CPython. The CFFI backend is really just for PyPy, even though it may technically work on CPython, it shouldn't be used. But this does point to the fact that I should be testing with pypy3, which would have revealed these issues.

**Comment by minrk** [comment]
@Arfrever would you like to make a pull request with your patch? I can apply it myself, if not, in which case would you like to give a name and email so I can give proper attribution?

**Comment by Arfrever** [comment]
Please apply patch. Including something like "Patch by Arfrever Frehtes Taifersar Arahesis" in commit message is sufficient.
