### ISSUE TITLE
zmq.tests.test_security.TestSecurity.test_curve(): Error with Python 2

### ISSUE THREAD

**Issue by Arfrever** [zeromq/pyzmq#685]
`zmq.tests.test_security.TestSecurity.test_curve()` often causes error with Python 2 (at least CPython 2.6 and 2.7) in both PyZMQ 14.6.0 and git trunk. This problem seems to not occur with Python 3.
I use ZeroMQ 4.1.1.

Result of test suite of PyZMQ git trunk with CPython 2.7:
```
$ PYTHONPATH="build/lib.linux-x86_64-2.7" nosetests-2.7 -s -v -w build/lib.linux-x86_64-2.7/zmq/tests
...
test_pyobj (zmq.tests.test_reqrep.TestReqRepGreen) ... ok
test CURVE encryption ... ERROR
test curve_keypair ... ok
...
======================================================================
ERROR: test CURVE encryption
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyzmq/build/lib.linux-x86_64-2.7/zmq/tests/test_security.py", line 210, in test_curve
    self.bounce(server, client)
  File "/tmp/pyzmq/build/lib.linux-x86_64-2.7/zmq/tests/test_security.py", line 83, in bounce
    self.assertEqual(frame.get('User-Id'), 'anonymous')
  File "zmq/backend/cython/message.pyx", line 375, in zmq.backend.cython.message.Frame.get (zmq/backend/cython/message.c:3418)
  File "zmq/backend/cython/checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/message.c:3999)
    raise ZMQError(errno)
ZMQError: Invalid argument

```

**Comment by minrk** [comment]
Does the test pass with zeromq 4.0?

**Comment by minrk** [comment]
Canyou try this again with current libzmq (4.1.2)? There were a number of bugs in 4.1.1.
