### ISSUE TITLE
socket bind in multi-process using python

### ISSUE THREAD

**Issue by gdpan919** [zeromq/pyzmq#758]
Hi, 

I used pyzmq in a multi-process program and came across the following crash. 
It is okay in a single process. Just report it to you,

Cheers,

Delvin
 

```
[Infor 2015-11-25 10:58:06 zmqwra 28 ] bind to tcp://192.168.0.47:93601
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./dataserver.py", line 59, in liveStream
    self.binder.bindPub(url)
  File "/home/delvin/code/python/eva/tools/zmqwrapper.py", line 159, in bindPub
    self.pub.bind(url)
  File "/home/delvin/code/python/eva/tools/zmqwrapper.py", line 29, in bind
    ret = self.socket.bind(self.ipport)
  File "zmq/backend/cython/socket.pyx", line 489, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:4824)
  File "zmq/backend/cython/checkrc.pxd", line 16, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6848)
    raise InterruptedSystemCall(errno)
InterruptedSystemCall: Interrupted system call: This call should have been retried. Please report this to pyzmq.
```

**Comment by minrk** [comment]
@gdpan919 can you provide some code to reproduce it?
