### ISSUE TITLE
zmq.utils z85 decode (of string) does not work with python 3

### ISSUE THREAD

**Issue by Sekenre** [zeromq/pyzmq#815]
I have been using the z85 encoding to store hashes in config files and sqlite database columns, while using python 2 I was able to assume that a z85 encoded value was simply a string. In migrating to python 3 I found that I needed to specify z85 as bytes.

Is this inconsistent with other encoding libraries? For example:
```
>>> import hashlib, base64
>>> type(hashlib.sha1(b'wibble').hexdigest())
<class 'str'>
>>> type(hashlib.sha1(b'wibble').digest())
<class 'bytes'>
>>> type(base64.b64encode(hashlib.sha1(b'wibble').digest()))
<class 'bytes'> # WAT?
```

I'm not sure which one is the right way to do it.

```
>>> print("libzmq-%s" % zmq.zmq_version())
libzmq-4.1.2
>>> print("pyzmq-%s" % zmq.pyzmq_version())
pyzmq-15.2.0
>>> print("Python-%s" % sys.version)
Python-3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
```

Steps to reproduce:
```
>>> z85.decode("Z9]q$")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Python\python-3.4.4\lib\site-packages\zmq\utils\z85.py", line 55, in decode
    value += Z85MAP[z85bytes[i+j]] * offset
KeyError: 'Z'
```
Expected behaviour from python 2.7:
```
>>> z85.decode("Z9]q$")
'\xbe(\x96\xd5'
```

Now I know I can fix this by prepending b"" to my string and it works as expected but should the decode function check whether I am passing in bytes or a string and raise a specific Exception? Or should it just automatically convert a string to a bytearray?

**Comment by Sekenre** [comment]
Pull request #816 is a possible fix for this

**Comment by Sekenre** [comment]
Actually, emulating the behaviour of hashlib under python3 might make more sense:

`TypeError: Unicode-objects must be encoded before hashing`

I will update my pull request
