### ISSUE TITLE
ZMQError "No such file or directory" thrown on unbind from random port

### ISSUE THREAD

**Issue by cmorse** [zeromq/pyzmq#824]
When binding a socket, using port "0", a ZMQError is thrown when unbinding.

I don't believe this is an issue with libzmq because we're using the same version in our C++ code and the same operation works correctly there.

Code to reproduce:

``` python
#!/usr/bin/env python

import sys
import zmq

print "libzmq-%s" % zmq.zmq_version()
print "pyzmq-%s" % zmq.pyzmq_version()
print "Python-%s" % sys.version

sock = zmq.Context.instance().socket(zmq.PUSH)
sock.bind("tcp://127.0.0.1:0")
address = sock.getsockopt_string(zmq.LAST_ENDPOINT)
print "Endpoint:%s" % address
sock.unbind(address)
```

Output from current stable version:

```
libzmq-4.0.5
pyzmq-15.2.0
Python-2.7.5 (default, Jun 24 2015, 00:41:19)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Endpoint:tcp://127.0.0.1:37980
Traceback (most recent call last):
  File "pyzmq_test.py", line 14, in <module>
    sock.unbind(address)
  File "zmq/backend/cython/socket.pyx", line 545, in zmq.backend.cython.socket.Socket.unbind (zmq/backend/cython/socket.c:5615)
zmq.error.ZMQError: No such file or directory
```

Output from current github master:

```
libzmq-4.0.5
pyzmq-15.3.0.dev
Python-2.7.5 (default, Jun 24 2015, 00:41:19)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Endpoing:tcp://127.0.0.1:55892
Traceback (most recent call last):
  File "pyzmq_test.py", line 14, in <module>
    sock.unbind(address)
  File "socket.pyx", line 564, in zmq.backend.cython.socket.Socket.unbind (zmq/backend/cython/socket.c:5405)
zmq.error.ZMQError: No such file or directory
```

**Comment by minrk** [comment]
With [this Dockerfile](https://gist.github.com/947724b52d46e4cd9fbee32c6d09466c), your script successfully unbinds from addresses with pyzmq-15.2 in fedora 20-23. I'm not sure what would be special about your system, but perhaps libzmq wasn't built correctly? How did you install libzmq and pyzmq?

**Comment by cmorse** [comment]
Sorry for the late reply on this. You are correct, I was using an out of sync version of libzmq.
