### ISSUE TITLE
zmq.green raise "filedescriptor out of range in select" under linux

### ISSUE THREAD

**Issue by honglei** [zeromq/pyzmq#844]
OS: CentOS 6
Python:3.5
gevent :1.2.0dev0

```
import gevent
from gevent import monkey
monkey.patch_all()
import zmq.green as zmq 

from gevent.server import StreamServer 

def echo(sock, address):
  poller = zmq.Poller()
  poller.register(sock, zmq.POLLIN|zmq.POLLOUT) 
  now = time.time()            
  socks = dict(poller.poll(timeout=200))
  ##..... 

server = StreamServer(('', 5000), echo)
server.serve_forever()
```

Traceback (most recent call last):
  File "/root/Python/Ntrip_Caster_work/gevent_test/gevent_tcp_server_zmqPoller.py", line 56, in echo
    socks = dict(poller.poll(timeout=200))
  File "/root/anaconda3/lib/python3.5/site-packages/zmq/green/poll.py", line 83, in poll
    select.select(rlist, wlist, xlist)
  File "/root/anaconda3/lib/python3.5/site-packages/gevent-1.2.0.dev0-py3.5-linux-x86_64.egg/gevent/select.py", line 141, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
ValueError: filedescriptor out of range in select()

**Comment by wojtossfm** [comment]
A bit late to the party, but what version of ZMQ and libzmq were you using? 

I ran into this issue recently. It was happening for me when libzmq that came with `pip install pyzmq==16.0.2` but wasn't happening when I compiled the same version (4.1.6) of libzmq locally and install pyzmq using `pip install pyzmq==16.0.2 --no-binary :all:`. 

Didn't have a chance yet to delve into the compilation flags of the libzmq that is shipped with the binary wheel and what is different, but thought I would leave this info here in case someone has time before I have a chance to look into it.
