### ISSUE TITLE
`socket.setsockopt(zmq.SUBSCRIBE, '')` fails when `from __future__ import unicode_literals` is used

### ISSUE THREAD

**Issue by gkapkowski** [zeromq/pyzmq#866]
```
Traceback (most recent call last):
  File "/apps/leds/start.py", line 11, in <module>
    inbound.setsockopt(zmq.SUBSCRIBE, '')
  File "zmq/backend/cython/socket.pyx", line 374, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4297)
TypeError: unicode not allowed, use setsockopt_string
```

**Comment by minrk** [comment]
Correct. `unicode_literals` means that anywhere you type `''`, it's actually doing `u''`, which is unicode, and SUBSCRIBE must be given bytes. To do this, use `b''`, which will work in both Python 2 and 3.
