### ISSUE TITLE
Update docs: zmq.asyncio.Poller.poll() fails with native sockets

### ISSUE THREAD

**Issue by jonkirsch** [zeromq/pyzmq#906]
Hello,

We tried creating a zmq.asyncio.Poller object, registering a native socket or fd, and then calling poll(), but doing so raises an exception that the add_recv_event method is not found.

```
Traceback (most recent call last):
  File "SimpleServer.py", line 311, in <module>
    ret = loop.run_until_complete(server.arun())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "SimpleServer.py", line 189, in arun
    sks = dict(await poller.poll(100))
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/future.py", line 65, in poll
    socket._add_recv_event('poll', future=watcher)
AttributeError: 'int' object has no attribute '_add_recv_event'

```
 Digging into the code, there is a comment that says the async version of the poller only supports polling on zmq sockets right now.

Recommend updating the docs to make this point clear. Apologies if I missed a note somewhere that warns us against doing this.

Thanks!

**Comment by minrk** [comment]
#907 should fix raw socket support.
