### ISSUE TITLE
[pypy] pyzmq linking fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by luav** [zeromq/pyzmq#915]
pyzmq linking fails on Ubuntu 16.04 using official Ubuntu packages:

```
julia> Pkg.build("IJulia")
INFO: Building Nettle
INFO: Building ZMQ
INFO: Building IJulia
INFO: Found Jupyter version 4.1.0: jupyter
Writing IJulia kernelspec to /home/lav/.julia/v0.5/IJulia/deps/julia-0.5/kernel.json ...
Installing julia kernelspec julia-0.5
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-kernelspec", line 7, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "/usr/local/lib/pypy2.7/dist-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/usr/local/lib/pypy2.7/dist-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/usr/local/lib/pypy2.7/dist-packages/zmq/__init__.py", line 44, in <module>
    _libsodium = ctypes.CDLL(bundled_sodium[0], mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/pypy/lib-python/2.7/ctypes/__init__.py", line 367, in __init__
    self._handle = _ffi.CDLL(name, mode)
OSError: Cannot load library /usr/local/lib/pypy2.7/dist-packages/zmq/libsodium.pypy-22.so: /usr/local/lib/pypy2.7/dist-packages/zmq/libsodium.pypy-22.so: undefined symbol: _Py_InitPyPyModule
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-kernelspec", line 7, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "/usr/local/lib/pypy2.7/dist-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/usr/local/lib/pypy2.7/dist-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/usr/local/lib/pypy2.7/dist-packages/zmq/__init__.py", line 44, in <module>
    _libsodium = ctypes.CDLL(bundled_sodium[0], mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/pypy/lib-python/2.7/ctypes/__init__.py", line 367, in __init__
    self._handle = _ffi.CDLL(name, mode)
OSError: Cannot load library /usr/local/lib/pypy2.7/dist-packages/zmq/libsodium.pypy-22.so: /usr/local/lib/pypy2.7/dist-packages/zmq/libsodium.pypy-22.so: undefined symbol: _Py_InitPyPyModule
```

```
$ ldconfig -p | grep "zmq"
    libzmq.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzmq.so.5
    libzmq.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzmq.so.3
    libzmq.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzmq.so.1
    libzmq.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzmq.so

$ dpkg -l "libzmq*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libzmq-dev:amd 2.2.0+dfsg-7 amd64        lightweight messaging kernel (dev
ii  libzmq1:amd64  2.2.0+dfsg-7 amd64        lightweight messaging kernel (sha
ii  libzmq3:amd64  4.0.4+dfsg-2 amd64        lightweight messaging kernel (sha
ii  libzmq5:amd64  4.1.4-7      amd64        lightweight messaging kernel (sha
```

If I use official libsodium and pylibsodium, and modify `zmq/__init__.py` with:
```
import ctypes.util
bundled_sodium = [ctypes.util.find_library('sodium') or ctypes.util.find_library('libsodium')]
```
then the following error occurs:
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-kernelspec", line 7, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "/usr/local/lib/pypy2.7/dist-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/usr/local/lib/pypy2.7/dist-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/usr/local/lib/pypy2.7/dist-packages/zmq/__init__.py", line 58, in <module>
    _libzmq = ctypes.CDLL(bundled[0], mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/pypy/lib-python/2.7/ctypes/__init__.py", line 367, in __init__
    self._handle = _ffi.CDLL(name, mode)
OSError: Cannot load library /usr/local/lib/pypy2.7/dist-packages/zmq/libzmq.pypy-22.so: /usr/local/lib/pypy2.7/dist-packages/zmq/libzmq.pypy-22.so: undefined symbol: _Py_InitPyPyModule
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-kernelspec", line 7, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "/usr/local/lib/pypy2.7/dist-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/usr/local/lib/pypy2.7/dist-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/usr/local/lib/pypy2.7/dist-packages/zmq/__init__.py", line 58, in <module>
    _libzmq = ctypes.CDLL(bundled[0], mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/pypy/lib-python/2.7/ctypes/__init__.py", line 367, in __init__
    self._handle = _ffi.CDLL(name, mode)
OSError: Cannot load library /usr/local/lib/pypy2.7/dist-packages/zmq/libzmq.pypy-22.so: /usr/local/lib/pypy2.7/dist-packages/zmq/libzmq.pypy-22.so: undefined symbol: _Py_InitPyPyModule
```

```
$ python --version
Python 2.7.12
```

**Comment by minrk** [comment]
Can you remove and reinstall pyzmq?

**Comment by minrk** [comment]
This kind of thing happens often when pyzmq is built against a version of libzmq, and that libzmq is upgraded without rebuilding pyzmq. Did you upgrade packages recently?

**Comment by luav** [comment]
I didn't notice at once that jupyter used pypy (not python) and zmq inside the pypy packages.
I reinstalled everything and ran under python, now it works, thanks!
