### ISSUE TITLE
zmq.error.Again raised from Socket.send from Cython w/o SNDTIMO

### ISSUE THREAD

**Issue by thehesiod** [zeromq/pyzmq#925]
See
```
Traceback (most recent call last):
  File "/weather/fbn/asyncio/workerpool.py", line 55, in _worker_loop
    result = await self._worker_co(*args, **kwargs)
  File "/s3sync/s3sync.py", line 417, in process_files
    response = await s3_client.head_object(Bucket=bucket, Key=content['Key'])
  File "/weather/fbn/asyncio/mp_worker_pool.py", line 447, in _call_helper
    await self._out_queue.send(pyobj)
  File "/weather/fbn/asyncio/zmq_utils.py", line 164, in send
    return await self._socket.send(data)
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/site-packages/zmq/eventloop/future.py", line 355, in _handle_send
    result = send(msg, **kwargs)
  File "zmq/backend/cython/socket.pyx", line 636, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6954)
  File "zmq/backend/cython/socket.pyx", line 683, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6698)
  File "zmq/backend/cython/socket.pyx", line 206, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2729)
  File "zmq/backend/cython/socket.pyx", line 201, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2617)
  File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9391)
zmq.error.Again: Resource temporarily unavailable```

I don't have a send timeout so I'm not sure how this is getting raised.

**Comment by minrk** [comment]
Do you have code to reproduce it?

**Comment by thehesiod** [comment]
unfortunately it's in a large project, I'll see if I can make a testcase

**Comment by minrk** [comment]
Thanks! I'll poke around, as well. My first guess is that it has something to do with two pending sends at the same time.

**Comment by thehesiod** [comment]
oh I can have > 100 sends going on at a time

**Comment by minrk** [comment]
If EAGAIN is triggering, that means a send is firing when POLLOUT is not set, which suggests that something along these lines is happening:

1. POLLOUT triggers
2. another send goes, filling HWM, unsetting POLLOUT
3. POLLOUT-triggered send fires, raising EAGAIN

I think I can add a check in _handle_send to make sure this doesn't happen (I see there's already a similar check in _handle_recv)

**Comment by thehesiod** [comment]
so in my scenario I set the HWM = 1, and if I allow for two concurrent sends eventually I get that error.  If I only do 1 I do not.

**Comment by minrk** [comment]
#927 should fix it if my understanding is correct.

**Comment by thehesiod** [comment]
testcase in 927
