### ISSUE TITLE
'zmq.backend.cython' has no attribute 'Stopwatch' with conda installed pyzmq

### ISSUE THREAD

**Issue by takluyver** [zeromq/pyzmq#931]
A couple of people here have just run into this error with PyZMQ installed by conda:

```
$ jupyter notebook 
Traceback (most recent call last):
  File "/Users/fangohr/anaconda3/envs/joommf/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/Users/fangohr/anaconda3/envs/joommf/lib/python3.5/site-packages/notebook/notebookapp.py", line 31, in <module>
    from zmq.eventloop import ioloop
  File "/Users/fangohr/anaconda3/envs/joommf/lib/python3.5/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/Users/fangohr/anaconda3/envs/joommf/lib/python3.5/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/Users/fangohr/anaconda3/envs/joommf/lib/python3.5/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/Users/fangohr/anaconda3/envs/joommf/lib/python3.5/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/Users/fangohr/anaconda3/envs/joommf/lib/python3.5/site-packages/zmq/backend/select.py", line 38, in select_backend
    ns[key] = getattr(mod, key)
AttributeError: module 'zmq.backend.cython' has no attribute 'Stopwatch'
```

We've seen this both on Linux and OSX. The version of pyzmq available in conda seems to be 15.4.0. Apologies if this is already known, but I couldn't find any other record of the error. Installing pyzmq 16.0.0 with pip worked OK.

**Comment by minrk** [comment]
This suggests that some files have been overwritten with pyzmq 16 (specifically, backend.cython is from 16, but select.py is from 15). I'm not sure how that would happen, but it seems likely to be either pip or conda having done something wrong.

**Comment by takluyver** [comment]
OK, so probably the recurring issue with hardlinked package files getting overwritten by pip. Thanks. The unfortunate consequence of two battling package managers that don't really know about each other.

**Comment by minrk** [comment]
Since pip uninstalls prior to install, I don't really understand how it would do this, but I think you're exactly right. Neither defaults nor conda-forge have pushed pyzmq-16 yet, so the 16 files are bound to have come from pip.
