### ISSUE TITLE
zmq.error.ZMQError: Invalid argument

### ISSUE THREAD

**Issue by del2z** [zeromq/pyzmq#944]
When I start Jupyter on Mac, I always get this error. I cannot figure it out. The version of libzmq and pyzmq are '4.2.0' and '16.0.1' respectively.
Below is traceback information when Jupyter accidentally shut down.
[I 19:21:45.831 NotebookApp] Kernel shutdown: 84633549-4ad1-46de-a80f-43b5264c736c
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/jupyter-notebook", line 11, in <module>
    load_entry_point('notebook==4.2.3', 'console_scripts', 'jupyter-notebook')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/notebook/notebookapp.py", line 1162, in start
    self.io_loop.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 183, in start
    raise e
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/ioloop.py", line 862, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 122, in poll
    z_events = self._poller.poll(1000*timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zmq/sugar/poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 122, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2177)
  File "zmq/backend/cython/_poll.pyx", line 115, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2027)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:2802)
zmq.error.ZMQError: Invalid argument

**Comment by minrk** [comment]
This is a bug in libzmq-4.2.0 (fixed in https://github.com/zeromq/libzmq/pull/2221), workaround already merged in #943. I'll cut 16.0.2 with the workaround shortly.

**Comment by kasturichavan** [comment]
@minrk Seems like pyzmq version 16.0.2 fixed this. 
Im using zeromq 4.1.4 & pyzmq used is 18.01 but i still this error. Do you why that would be the case ?
