### ISSUE TITLE
test_auth test_security random fails and hangs in debian

### ISSUE THREAD

**Issue by juliantaylor** [zeromq/pyzmq#953]
with pyzmq 16.0.2 and also earlier versions some tests randomly fail or hang indefinitely.
The failures are quite rare, maybe one in 10 runs. It appears to happen with all supported python versions including pypy, but somewhat more common with the debug versions of the interpreters and slow machines.
Reproducable in current debian unstable with zeromq 4.2.0, but it also affected other versions e.g. 4.1 and 4.0.

TestSecurity.test_plain

```
=================================== FAILURES ===================================
___________________________ TestSecurity.test_plain ____________________________

self = <zmq.tests.test_security.TestSecurity testMethod=test_plain>

    def test_plain(self):
        """test PLAIN authentication"""
        server = self.socket(zmq.DEALER)
        server.identity = b'IDENT'
        client = self.socket(zmq.DEALER)
        self.assertEqual(client.plain_username, b'')
        self.assertEqual(client.plain_password, b'')
        client.plain_username = USER
        client.plain_password = PASS
        self.assertEqual(client.getsockopt(zmq.PLAIN_USERNAME), USER)
        self.assertEqual(client.getsockopt(zmq.PLAIN_PASSWORD), PASS)
        self.assertEqual(client.plain_server, 0)
        self.assertEqual(server.plain_server, 0)
        server.plain_server = True
        self.assertEqual(server.mechanism, zmq.PLAIN)
        self.assertEqual(client.mechanism, zmq.PLAIN)
    
        assert not client.plain_server
        assert server.plain_server
    
        self.start_zap()
    
        iface = 'tcp://127.0.0.1'
        port = server.bind_to_random_port(iface)
        client.connect("%s:%i" % (iface, port))
>       self.bounce(server, client)

zmq/tests/test_security.py:132: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
zmq/tests/test_security.py:83: in bounce
    self.assertEqual(frame.get('User-Id'), 'anonymous')
zmq/backend/cython/message.pyx:375: in zmq.backend.cython.message.Frame.get (zmq/backend/cython/message.c:3950)
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   raise ZMQError(errno)
E   ZMQError: Invalid argument

zmq/backend/cython/checkrc.pxd:25: ZMQError
--------------------------- Captured stderr teardown ---------------------------
Exception in thread Thread-195:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y-dbg_2.7/build/zmq/tests/test_security.py", line 36, in zap_handler
    msg = self.recv_multipart(socket)
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y-dbg_2.7/build/zmq/tests/__init__.py", line 144, in recv_multipart
    return self._select_recv(True, socket, **kwargs)
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y-dbg_2.7/build/zmq/tests/__init__.py", line 131, in _select_recv
    r,w,x = zmq.select([socket], [], [], timeout=5)
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y-dbg_2.7/build/zmq/sugar/poll.py", line 143, in select
    return_sockets = zmq_poll(sockets, timeout)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2195)
  File "zmq/backend/cython/_poll.pyx", line 116, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2045)
  File "zmq/backend/cython/checkrc.pxd", line 22, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:2729)
    raise ContextTerminated(errno)
ContextTerminated: Context was terminated
```

TestSecurity.test_curve

```
=================================== FAILURES ===================================
___________________________ TestSecurity.test_curve ____________________________

self = <zmq.tests.test_security.TestSecurity testMethod=test_curve>

    def test_curve(self):
        """test CURVE encryption"""
        server = self.socket(zmq.DEALER)
        server.identity = b'IDENT'
        client = self.socket(zmq.DEALER)
        self.sockets.extend([server, client])
        try:
            server.curve_server = True
        except zmq.ZMQError as e:
            # will raise EINVAL if no CURVE support
            if e.errno == zmq.EINVAL:
                raise SkipTest("CURVE unsupported")
    
        server_public, server_secret = zmq.curve_keypair()
        client_public, client_secret = zmq.curve_keypair()
    
        server.curve_secretkey = server_secret
        server.curve_publickey = server_public
        client.curve_serverkey = server_public
        client.curve_publickey = client_public
        client.curve_secretkey = client_secret
    
        self.assertEqual(server.mechanism, zmq.CURVE)
        self.assertEqual(client.mechanism, zmq.CURVE)
    
        self.assertEqual(server.get(zmq.CURVE_SERVER), True)
        self.assertEqual(client.get(zmq.CURVE_SERVER), False)
    
        self.start_zap()
    
        iface = 'tcp://127.0.0.1'
        port = server.bind_to_random_port(iface)
        client.connect("%s:%i" % (iface, port))
>       self.bounce(server, client)

zmq/tests/test_security.py:210: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
zmq/tests/test_security.py:83: in bounce
    self.assertEqual(frame.get('User-Id'), 'anonymous')
zmq/backend/cython/message.pyx:375: in zmq.backend.cython.message.Frame.get (zmq/backend/cython/message.c:3950)
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   raise ZMQError(errno)
E   ZMQError: Invalid argument

zmq/backend/cython/checkrc.pxd:25: ZMQError
--------------------------- Captured stderr teardown ---------------------------
Exception in thread Thread-191:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y-dbg_2.7/build/zmq/tests/test_security.py", line 36, in zap_handler
    msg = self.recv_multipart(socket)
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y-dbg_2.7/build/zmq/tests/__init__.py", line 144, in recv_multipart
    return self._select_recv(True, socket, **kwargs)
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y-dbg_2.7/build/zmq/tests/__init__.py", line 131, in _select_recv
    r,w,x = zmq.select([socket], [], [], timeout=5)
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y-dbg_2.7/build/zmq/sugar/poll.py", line 143, in select
    return_sockets = zmq_poll(sockets, timeout)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2195)
  File "zmq/backend/cython/_poll.pyx", line 116, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2045)
  File "zmq/backend/cython/checkrc.pxd", line 22, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:2729)
    raise ContextTerminated(errno)
ContextTerminated: Context was terminated
```

`zmq/tests/test_auth.py` sometimes just hangs forever instead of failing, but it is not always the same test, sometimes it hangs on the very first other times it executes a couple before it hangs.

full logs, note they are on some of debians uncommon arches, but I have seen all failures on x86 too.
https://buildd.debian.org/status/fetch.php?pkg=pyzmq&arch=mips64el&ver=16.0.2-1&stamp=1482416208
https://buildd.debian.org/status/fetch.php?pkg=pyzmq&arch=ppc64el&ver=16.0.2-1&stamp=1482425168
https://buildd.debian.org/status/fetch.php?pkg=pyzmq&arch=s390x&ver=16.0.2-1&stamp=1482415803

**Comment by minrk** [comment]
Thanks, I'll see what I can find out. Seems likely to be races, since there are IO threads involved, but I'm not sure how User-Id could be missing, which is what the EINVAL suggests.
