### ISSUE TITLE
IOLoop.close(all_fds=True) can raise RuntimeError

### ISSUE THREAD

**Issue by pitrou** [zeromq/pyzmq#963]
```
Traceback (most recent call last):
  File "/home/antoine/distributed/distributed/utils_test.py", line 435, in test_func
    loop.stop()
  File "/home/antoine/miniconda3/envs/dask35/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/antoine/distributed/distributed/utils_test.py", line 109, in pristine_loop
    loop.close(all_fds=True)
  File "/home/antoine/tornado/tornado/ioloop.py", line 719, in close
    for fd, handler in self._handlers.values():
RuntimeError: dictionary changed size during iteration
```

The explanation: `IOLoop.close(all_fds=True)` calls `.close()` on each iterated socket object, and `_AsyncSocket.close` calls `IOLoop.remove_handler()` immediately.

**Comment by minrk** [comment]
Good catch. It should still remove the handler in other cases. My inclination is a two-fold fix:

1. (safely) check private `IOLoop._closing` flag  in `FutureSocket.close` to prevent this in current versions of tornado
2. push a fix upstream to tornado to call `list(self._handlers.values())` in close, so that it's not sensitive to the dict changing size during iteration
