### ISSUE TITLE
Unable to bind to IPV6 address

### ISSUE THREAD

**Issue by ccaapton** [zeromq/pyzmq#989]
When I'm trying to bind a publish socket on ipv6 as following:

```
import zmq
c = zmq.Context()
s = c.socket(zmq.PUB)
s.bind('tcp://[2602:ff96:9::9dce:3092]:5060')
```

I got the follow error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "zmq/backend/cython/socket.pyx", line 444, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:4089)
  File "zmq/backend/cython/checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6248)
zmq.error.ZMQError: No such device
```
How can I solve this? Thanks a lot!

**Comment by ccaapton** [comment]
Sorry, I should have found the solution myself. The answer is that I need:
```
c.setsockopt(zmq.IPV6,1)
```

**Comment by minrk** [comment]
Glad you got it! I'm not sure why this isn't enabled by default in libzmq.
